// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/common.proto
// Protobuf Java Version: 4.29.2

package io.chirpstack.api;

public final class CommonProto {
  private CommonProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      CommonProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_Location_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_Location_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_KeyEnvelope_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_KeyEnvelope_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_Metric_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_Metric_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_MetricDataset_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_MetricDataset_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_JoinServerContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_JoinServerContext_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023common/common.proto\022\006common\032\037google/pr" +
      "otobuf/timestamp.proto\"{\n\010Location\022\020\n\010la" +
      "titude\030\001 \001(\001\022\021\n\tlongitude\030\002 \001(\001\022\020\n\010altit" +
      "ude\030\003 \001(\001\022&\n\006source\030\004 \001(\0162\026.common.Locat" +
      "ionSource\022\020\n\010accuracy\030\005 \001(\002\"1\n\013KeyEnvelo" +
      "pe\022\021\n\tkek_label\030\001 \001(\t\022\017\n\007aes_key\030\002 \001(\014\"\221" +
      "\001\n\006Metric\022\014\n\004name\030\001 \001(\t\022.\n\ntimestamps\030\002 " +
      "\003(\0132\032.google.protobuf.Timestamp\022\'\n\010datas" +
      "ets\030\003 \003(\0132\025.common.MetricDataset\022 \n\004kind" +
      "\030\004 \001(\0162\022.common.MetricKind\",\n\rMetricData" +
      "set\022\r\n\005label\030\001 \001(\t\022\014\n\004data\030\002 \003(\002\"S\n\021Join" +
      "ServerContext\022\026\n\016session_key_id\030\001 \001(\t\022&\n" +
      "\tapp_s_key\030\002 \001(\0132\023.common.KeyEnvelope*,\n" +
      "\nModulation\022\010\n\004LORA\020\000\022\007\n\003FSK\020\001\022\013\n\007LR_FHS" +
      "S\020\002*\252\001\n\006Region\022\t\n\005EU868\020\000\022\t\n\005US915\020\002\022\t\n\005" +
      "CN779\020\003\022\t\n\005EU433\020\004\022\t\n\005AU915\020\005\022\t\n\005CN470\020\006" +
      "\022\t\n\005AS923\020\007\022\013\n\007AS923_2\020\014\022\013\n\007AS923_3\020\r\022\013\n" +
      "\007AS923_4\020\016\022\t\n\005KR920\020\010\022\t\n\005IN865\020\t\022\t\n\005RU86" +
      "4\020\n\022\013\n\007ISM2400\020\013*\263\001\n\005MType\022\020\n\014JOIN_REQUE" +
      "ST\020\000\022\017\n\013JOIN_ACCEPT\020\001\022\027\n\023UNCONFIRMED_DAT" +
      "A_UP\020\002\022\031\n\025UNCONFIRMED_DATA_DOWN\020\003\022\025\n\021CON" +
      "FIRMED_DATA_UP\020\004\022\027\n\023CONFIRMED_DATA_DOWN\020" +
      "\005\022\022\n\016REJOIN_REQUEST\020\006\022\017\n\013PROPRIETARY\020\007*~" +
      "\n\nMacVersion\022\021\n\rLORAWAN_1_0_0\020\000\022\021\n\rLORAW" +
      "AN_1_0_1\020\001\022\021\n\rLORAWAN_1_0_2\020\002\022\021\n\rLORAWAN" +
      "_1_0_3\020\003\022\021\n\rLORAWAN_1_0_4\020\004\022\021\n\rLORAWAN_1" +
      "_1_0\020\005*v\n\021RegParamsRevision\022\005\n\001A\020\000\022\005\n\001B\020" +
      "\001\022\017\n\013RP002_1_0_0\020\002\022\017\n\013RP002_1_0_1\020\003\022\017\n\013R" +
      "P002_1_0_2\020\004\022\017\n\013RP002_1_0_3\020\005\022\017\n\013RP002_1" +
      "_0_4\020\006*\216\001\n\016LocationSource\022\013\n\007UNKNOWN\020\000\022\007" +
      "\n\003GPS\020\001\022\n\n\006CONFIG\020\002\022\025\n\021GEO_RESOLVER_TDOA" +
      "\020\003\022\025\n\021GEO_RESOLVER_RSSI\020\004\022\025\n\021GEO_RESOLVE" +
      "R_GNSS\020\005\022\025\n\021GEO_RESOLVER_WIFI\020\006*7\n\013Aggre" +
      "gation\022\010\n\004HOUR\020\000\022\007\n\003DAY\020\001\022\t\n\005MONTH\020\002\022\n\n\006" +
      "MINUTE\020\003*2\n\nMetricKind\022\013\n\007COUNTER\020\000\022\014\n\010A" +
      "BSOLUTE\020\001\022\t\n\005GAUGE\020\002*9\n\nRegulation\022\026\n\022RE" +
      "GULATION_UNKNOWN\020\000\022\023\n\017ETSI_EN_300_220\020\001*" +
      "4\n\013DeviceClass\022\013\n\007CLASS_A\020\000\022\013\n\007CLASS_B\020\001" +
      "\022\013\n\007CLASS_C\020\002B\235\001\n\021io.chirpstack.apiB\013Com" +
      "monProtoP\001Z1github.com/chirpstack/chirps" +
      "tack/api/go/v4/common\252\002\021Chirpstack.Commo" +
      "n\312\002\021Chirpstack\\Common\342\002\035GPBMetadata\\Chir" +
      "pstack\\Commonb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_common_Location_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_Location_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "Altitude", "Source", "Accuracy", });
    internal_static_common_KeyEnvelope_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_common_KeyEnvelope_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_KeyEnvelope_descriptor,
        new java.lang.String[] { "KekLabel", "AesKey", });
    internal_static_common_Metric_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_common_Metric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_Metric_descriptor,
        new java.lang.String[] { "Name", "Timestamps", "Datasets", "Kind", });
    internal_static_common_MetricDataset_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_common_MetricDataset_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_MetricDataset_descriptor,
        new java.lang.String[] { "Label", "Data", });
    internal_static_common_JoinServerContext_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_common_JoinServerContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_JoinServerContext_descriptor,
        new java.lang.String[] { "SessionKeyId", "AppSKey", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
