// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/device.proto

package io.chirpstack.api;

public interface DeviceStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.DeviceStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The device margin status
   * -32..32: The demodulation SNR ration in dB
   * </pre>
   *
   * <code>int32 margin = 1;</code>
   * @return The margin.
   */
  int getMargin();

  /**
   * <pre>
   * Device is connected to an external power source.
   * </pre>
   *
   * <code>bool external_power_source = 2;</code>
   * @return The externalPowerSource.
   */
  boolean getExternalPowerSource();

  /**
   * <pre>
   * Device battery level as a percentage.
   * -1 when the battery level is not available.
   * </pre>
   *
   * <code>float battery_level = 3;</code>
   * @return The batteryLevel.
   */
  float getBatteryLevel();
}
