// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/frame_log.proto

package io.chirpstack.api;

/**
 * Protobuf type {@code api.DownlinkFrameLog}
 */
public final class DownlinkFrameLog extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.DownlinkFrameLog)
    DownlinkFrameLogOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DownlinkFrameLog.newBuilder() to construct.
  private DownlinkFrameLog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DownlinkFrameLog() {
    phyPayload_ = com.google.protobuf.ByteString.EMPTY;
    gatewayId_ = "";
    mType_ = 0;
    devAddr_ = "";
    devEui_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new DownlinkFrameLog();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return FrameLogProto.internal_static_api_DownlinkFrameLog_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return FrameLogProto.internal_static_api_DownlinkFrameLog_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            DownlinkFrameLog.class, Builder.class);
  }

  public static final int TIME_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp time_;
  /**
   * <pre>
   * Time.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 1;</code>
   * @return Whether the time field is set.
   */
  @Override
  public boolean hasTime() {
    return time_ != null;
  }
  /**
   * <pre>
   * Time.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 1;</code>
   * @return The time.
   */
  @Override
  public com.google.protobuf.Timestamp getTime() {
    return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
  }
  /**
   * <pre>
   * Time.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 1;</code>
   */
  @Override
  public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
    return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
  }

  public static final int PHY_PAYLOAD_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString phyPayload_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * PHYPayload.
   * </pre>
   *
   * <code>bytes phy_payload = 2;</code>
   * @return The phyPayload.
   */
  @Override
  public com.google.protobuf.ByteString getPhyPayload() {
    return phyPayload_;
  }

  public static final int TX_INFO_FIELD_NUMBER = 3;
  private io.chirpstack.api.gw.DownlinkTxInfo txInfo_;
  /**
   * <pre>
   * TX meta-data.
   * </pre>
   *
   * <code>.gw.DownlinkTxInfo tx_info = 3;</code>
   * @return Whether the txInfo field is set.
   */
  @Override
  public boolean hasTxInfo() {
    return txInfo_ != null;
  }
  /**
   * <pre>
   * TX meta-data.
   * </pre>
   *
   * <code>.gw.DownlinkTxInfo tx_info = 3;</code>
   * @return The txInfo.
   */
  @Override
  public io.chirpstack.api.gw.DownlinkTxInfo getTxInfo() {
    return txInfo_ == null ? io.chirpstack.api.gw.DownlinkTxInfo.getDefaultInstance() : txInfo_;
  }
  /**
   * <pre>
   * TX meta-data.
   * </pre>
   *
   * <code>.gw.DownlinkTxInfo tx_info = 3;</code>
   */
  @Override
  public io.chirpstack.api.gw.DownlinkTxInfoOrBuilder getTxInfoOrBuilder() {
    return txInfo_ == null ? io.chirpstack.api.gw.DownlinkTxInfo.getDefaultInstance() : txInfo_;
  }

  public static final int DOWNLINK_ID_FIELD_NUMBER = 4;
  private int downlinkId_ = 0;
  /**
   * <pre>
   * Downlink ID.
   * </pre>
   *
   * <code>uint32 downlink_id = 4;</code>
   * @return The downlinkId.
   */
  @Override
  public int getDownlinkId() {
    return downlinkId_;
  }

  public static final int GATEWAY_ID_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile Object gatewayId_ = "";
  /**
   * <pre>
   * Gateway ID (EUI64).
   * </pre>
   *
   * <code>string gateway_id = 5;</code>
   * @return The gatewayId.
   */
  @Override
  public String getGatewayId() {
    Object ref = gatewayId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      gatewayId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Gateway ID (EUI64).
   * </pre>
   *
   * <code>string gateway_id = 5;</code>
   * @return The bytes for gatewayId.
   */
  @Override
  public com.google.protobuf.ByteString
      getGatewayIdBytes() {
    Object ref = gatewayId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      gatewayId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int M_TYPE_FIELD_NUMBER = 6;
  private int mType_ = 0;
  /**
   * <pre>
   * Message type.
   * </pre>
   *
   * <code>.common.MType m_type = 6;</code>
   * @return The enum numeric value on the wire for mType.
   */
  @Override public int getMTypeValue() {
    return mType_;
  }
  /**
   * <pre>
   * Message type.
   * </pre>
   *
   * <code>.common.MType m_type = 6;</code>
   * @return The mType.
   */
  @Override public io.chirpstack.api.MType getMType() {
    io.chirpstack.api.MType result = io.chirpstack.api.MType.forNumber(mType_);
    return result == null ? io.chirpstack.api.MType.UNRECOGNIZED : result;
  }

  public static final int DEV_ADDR_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile Object devAddr_ = "";
  /**
   * <pre>
   * Device address (optional).
   * </pre>
   *
   * <code>string dev_addr = 7;</code>
   * @return The devAddr.
   */
  @Override
  public String getDevAddr() {
    Object ref = devAddr_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      devAddr_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Device address (optional).
   * </pre>
   *
   * <code>string dev_addr = 7;</code>
   * @return The bytes for devAddr.
   */
  @Override
  public com.google.protobuf.ByteString
      getDevAddrBytes() {
    Object ref = devAddr_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      devAddr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEV_EUI_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile Object devEui_ = "";
  /**
   * <pre>
   * Device EUI (optional).
   * </pre>
   *
   * <code>string dev_eui = 8;</code>
   * @return The devEui.
   */
  @Override
  public String getDevEui() {
    Object ref = devEui_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      devEui_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Device EUI (optional).
   * </pre>
   *
   * <code>string dev_eui = 8;</code>
   * @return The bytes for devEui.
   */
  @Override
  public com.google.protobuf.ByteString
      getDevEuiBytes() {
    Object ref = devEui_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      devEui_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAINTEXT_MAC_COMMANDS_FIELD_NUMBER = 9;
  private boolean plaintextMacCommands_ = false;
  /**
   * <pre>
   * Plaintext mac-commands.
   * </pre>
   *
   * <code>bool plaintext_mac_commands = 9;</code>
   * @return The plaintextMacCommands.
   */
  @Override
  public boolean getPlaintextMacCommands() {
    return plaintextMacCommands_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (time_ != null) {
      output.writeMessage(1, getTime());
    }
    if (!phyPayload_.isEmpty()) {
      output.writeBytes(2, phyPayload_);
    }
    if (txInfo_ != null) {
      output.writeMessage(3, getTxInfo());
    }
    if (downlinkId_ != 0) {
      output.writeUInt32(4, downlinkId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gatewayId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, gatewayId_);
    }
    if (mType_ != io.chirpstack.api.MType.JOIN_REQUEST.getNumber()) {
      output.writeEnum(6, mType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(devAddr_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, devAddr_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(devEui_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, devEui_);
    }
    if (plaintextMacCommands_ != false) {
      output.writeBool(9, plaintextMacCommands_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (time_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTime());
    }
    if (!phyPayload_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, phyPayload_);
    }
    if (txInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTxInfo());
    }
    if (downlinkId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, downlinkId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gatewayId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, gatewayId_);
    }
    if (mType_ != io.chirpstack.api.MType.JOIN_REQUEST.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, mType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(devAddr_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, devAddr_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(devEui_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, devEui_);
    }
    if (plaintextMacCommands_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, plaintextMacCommands_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof DownlinkFrameLog)) {
      return super.equals(obj);
    }
    DownlinkFrameLog other = (DownlinkFrameLog) obj;

    if (hasTime() != other.hasTime()) return false;
    if (hasTime()) {
      if (!getTime()
          .equals(other.getTime())) return false;
    }
    if (!getPhyPayload()
        .equals(other.getPhyPayload())) return false;
    if (hasTxInfo() != other.hasTxInfo()) return false;
    if (hasTxInfo()) {
      if (!getTxInfo()
          .equals(other.getTxInfo())) return false;
    }
    if (getDownlinkId()
        != other.getDownlinkId()) return false;
    if (!getGatewayId()
        .equals(other.getGatewayId())) return false;
    if (mType_ != other.mType_) return false;
    if (!getDevAddr()
        .equals(other.getDevAddr())) return false;
    if (!getDevEui()
        .equals(other.getDevEui())) return false;
    if (getPlaintextMacCommands()
        != other.getPlaintextMacCommands()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTime()) {
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
    }
    hash = (37 * hash) + PHY_PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getPhyPayload().hashCode();
    if (hasTxInfo()) {
      hash = (37 * hash) + TX_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getTxInfo().hashCode();
    }
    hash = (37 * hash) + DOWNLINK_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDownlinkId();
    hash = (37 * hash) + GATEWAY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getGatewayId().hashCode();
    hash = (37 * hash) + M_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + mType_;
    hash = (37 * hash) + DEV_ADDR_FIELD_NUMBER;
    hash = (53 * hash) + getDevAddr().hashCode();
    hash = (37 * hash) + DEV_EUI_FIELD_NUMBER;
    hash = (53 * hash) + getDevEui().hashCode();
    hash = (37 * hash) + PLAINTEXT_MAC_COMMANDS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPlaintextMacCommands());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static DownlinkFrameLog parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DownlinkFrameLog parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DownlinkFrameLog parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DownlinkFrameLog parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DownlinkFrameLog parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DownlinkFrameLog parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DownlinkFrameLog parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DownlinkFrameLog parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static DownlinkFrameLog parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static DownlinkFrameLog parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static DownlinkFrameLog parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DownlinkFrameLog parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(DownlinkFrameLog prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.DownlinkFrameLog}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.DownlinkFrameLog)
      DownlinkFrameLogOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FrameLogProto.internal_static_api_DownlinkFrameLog_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FrameLogProto.internal_static_api_DownlinkFrameLog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DownlinkFrameLog.class, Builder.class);
    }

    // Construct using io.chirpstack.api.DownlinkFrameLog.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      time_ = null;
      if (timeBuilder_ != null) {
        timeBuilder_.dispose();
        timeBuilder_ = null;
      }
      phyPayload_ = com.google.protobuf.ByteString.EMPTY;
      txInfo_ = null;
      if (txInfoBuilder_ != null) {
        txInfoBuilder_.dispose();
        txInfoBuilder_ = null;
      }
      downlinkId_ = 0;
      gatewayId_ = "";
      mType_ = 0;
      devAddr_ = "";
      devEui_ = "";
      plaintextMacCommands_ = false;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return FrameLogProto.internal_static_api_DownlinkFrameLog_descriptor;
    }

    @Override
    public DownlinkFrameLog getDefaultInstanceForType() {
      return DownlinkFrameLog.getDefaultInstance();
    }

    @Override
    public DownlinkFrameLog build() {
      DownlinkFrameLog result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public DownlinkFrameLog buildPartial() {
      DownlinkFrameLog result = new DownlinkFrameLog(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(DownlinkFrameLog result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.time_ = timeBuilder_ == null
            ? time_
            : timeBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.phyPayload_ = phyPayload_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.txInfo_ = txInfoBuilder_ == null
            ? txInfo_
            : txInfoBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.downlinkId_ = downlinkId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.gatewayId_ = gatewayId_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.mType_ = mType_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.devAddr_ = devAddr_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.devEui_ = devEui_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.plaintextMacCommands_ = plaintextMacCommands_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DownlinkFrameLog) {
        return mergeFrom((DownlinkFrameLog)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DownlinkFrameLog other) {
      if (other == DownlinkFrameLog.getDefaultInstance()) return this;
      if (other.hasTime()) {
        mergeTime(other.getTime());
      }
      if (other.getPhyPayload() != com.google.protobuf.ByteString.EMPTY) {
        setPhyPayload(other.getPhyPayload());
      }
      if (other.hasTxInfo()) {
        mergeTxInfo(other.getTxInfo());
      }
      if (other.getDownlinkId() != 0) {
        setDownlinkId(other.getDownlinkId());
      }
      if (!other.getGatewayId().isEmpty()) {
        gatewayId_ = other.gatewayId_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.mType_ != 0) {
        setMTypeValue(other.getMTypeValue());
      }
      if (!other.getDevAddr().isEmpty()) {
        devAddr_ = other.devAddr_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getDevEui().isEmpty()) {
        devEui_ = other.devEui_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.getPlaintextMacCommands() != false) {
        setPlaintextMacCommands(other.getPlaintextMacCommands());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              phyPayload_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getTxInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              downlinkId_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              gatewayId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              mType_ = input.readEnum();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              devAddr_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              devEui_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 72: {
              plaintextMacCommands_ = input.readBool();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Timestamp time_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timeBuilder_;
    /**
     * <pre>
     * Time.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 1;</code>
     * @return Whether the time field is set.
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Time.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 1;</code>
     * @return The time.
     */
    public com.google.protobuf.Timestamp getTime() {
      if (timeBuilder_ == null) {
        return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
      } else {
        return timeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Time.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 1;</code>
     */
    public Builder setTime(com.google.protobuf.Timestamp value) {
      if (timeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        time_ = value;
      } else {
        timeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Time.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 1;</code>
     */
    public Builder setTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timeBuilder_ == null) {
        time_ = builderForValue.build();
      } else {
        timeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Time.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 1;</code>
     */
    public Builder mergeTime(com.google.protobuf.Timestamp value) {
      if (timeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          time_ != null &&
          time_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getTimeBuilder().mergeFrom(value);
        } else {
          time_ = value;
        }
      } else {
        timeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Time.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 1;</code>
     */
    public Builder clearTime() {
      bitField0_ = (bitField0_ & ~0x00000001);
      time_ = null;
      if (timeBuilder_ != null) {
        timeBuilder_.dispose();
        timeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Time.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 1;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimeBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Time.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
      if (timeBuilder_ != null) {
        return timeBuilder_.getMessageOrBuilder();
      } else {
        return time_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : time_;
      }
    }
    /**
     * <pre>
     * Time.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimeFieldBuilder() {
      if (timeBuilder_ == null) {
        timeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTime(),
                getParentForChildren(),
                isClean());
        time_ = null;
      }
      return timeBuilder_;
    }

    private com.google.protobuf.ByteString phyPayload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * PHYPayload.
     * </pre>
     *
     * <code>bytes phy_payload = 2;</code>
     * @return The phyPayload.
     */
    @Override
    public com.google.protobuf.ByteString getPhyPayload() {
      return phyPayload_;
    }
    /**
     * <pre>
     * PHYPayload.
     * </pre>
     *
     * <code>bytes phy_payload = 2;</code>
     * @param value The phyPayload to set.
     * @return This builder for chaining.
     */
    public Builder setPhyPayload(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      phyPayload_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PHYPayload.
     * </pre>
     *
     * <code>bytes phy_payload = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhyPayload() {
      bitField0_ = (bitField0_ & ~0x00000002);
      phyPayload_ = getDefaultInstance().getPhyPayload();
      onChanged();
      return this;
    }

    private io.chirpstack.api.gw.DownlinkTxInfo txInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.chirpstack.api.gw.DownlinkTxInfo, io.chirpstack.api.gw.DownlinkTxInfo.Builder, io.chirpstack.api.gw.DownlinkTxInfoOrBuilder> txInfoBuilder_;
    /**
     * <pre>
     * TX meta-data.
     * </pre>
     *
     * <code>.gw.DownlinkTxInfo tx_info = 3;</code>
     * @return Whether the txInfo field is set.
     */
    public boolean hasTxInfo() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * TX meta-data.
     * </pre>
     *
     * <code>.gw.DownlinkTxInfo tx_info = 3;</code>
     * @return The txInfo.
     */
    public io.chirpstack.api.gw.DownlinkTxInfo getTxInfo() {
      if (txInfoBuilder_ == null) {
        return txInfo_ == null ? io.chirpstack.api.gw.DownlinkTxInfo.getDefaultInstance() : txInfo_;
      } else {
        return txInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * TX meta-data.
     * </pre>
     *
     * <code>.gw.DownlinkTxInfo tx_info = 3;</code>
     */
    public Builder setTxInfo(io.chirpstack.api.gw.DownlinkTxInfo value) {
      if (txInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        txInfo_ = value;
      } else {
        txInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * TX meta-data.
     * </pre>
     *
     * <code>.gw.DownlinkTxInfo tx_info = 3;</code>
     */
    public Builder setTxInfo(
        io.chirpstack.api.gw.DownlinkTxInfo.Builder builderForValue) {
      if (txInfoBuilder_ == null) {
        txInfo_ = builderForValue.build();
      } else {
        txInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * TX meta-data.
     * </pre>
     *
     * <code>.gw.DownlinkTxInfo tx_info = 3;</code>
     */
    public Builder mergeTxInfo(io.chirpstack.api.gw.DownlinkTxInfo value) {
      if (txInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          txInfo_ != null &&
          txInfo_ != io.chirpstack.api.gw.DownlinkTxInfo.getDefaultInstance()) {
          getTxInfoBuilder().mergeFrom(value);
        } else {
          txInfo_ = value;
        }
      } else {
        txInfoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * TX meta-data.
     * </pre>
     *
     * <code>.gw.DownlinkTxInfo tx_info = 3;</code>
     */
    public Builder clearTxInfo() {
      bitField0_ = (bitField0_ & ~0x00000004);
      txInfo_ = null;
      if (txInfoBuilder_ != null) {
        txInfoBuilder_.dispose();
        txInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * TX meta-data.
     * </pre>
     *
     * <code>.gw.DownlinkTxInfo tx_info = 3;</code>
     */
    public io.chirpstack.api.gw.DownlinkTxInfo.Builder getTxInfoBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getTxInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * TX meta-data.
     * </pre>
     *
     * <code>.gw.DownlinkTxInfo tx_info = 3;</code>
     */
    public io.chirpstack.api.gw.DownlinkTxInfoOrBuilder getTxInfoOrBuilder() {
      if (txInfoBuilder_ != null) {
        return txInfoBuilder_.getMessageOrBuilder();
      } else {
        return txInfo_ == null ?
            io.chirpstack.api.gw.DownlinkTxInfo.getDefaultInstance() : txInfo_;
      }
    }
    /**
     * <pre>
     * TX meta-data.
     * </pre>
     *
     * <code>.gw.DownlinkTxInfo tx_info = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.chirpstack.api.gw.DownlinkTxInfo, io.chirpstack.api.gw.DownlinkTxInfo.Builder, io.chirpstack.api.gw.DownlinkTxInfoOrBuilder> 
        getTxInfoFieldBuilder() {
      if (txInfoBuilder_ == null) {
        txInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.chirpstack.api.gw.DownlinkTxInfo, io.chirpstack.api.gw.DownlinkTxInfo.Builder, io.chirpstack.api.gw.DownlinkTxInfoOrBuilder>(
                getTxInfo(),
                getParentForChildren(),
                isClean());
        txInfo_ = null;
      }
      return txInfoBuilder_;
    }

    private int downlinkId_ ;
    /**
     * <pre>
     * Downlink ID.
     * </pre>
     *
     * <code>uint32 downlink_id = 4;</code>
     * @return The downlinkId.
     */
    @Override
    public int getDownlinkId() {
      return downlinkId_;
    }
    /**
     * <pre>
     * Downlink ID.
     * </pre>
     *
     * <code>uint32 downlink_id = 4;</code>
     * @param value The downlinkId to set.
     * @return This builder for chaining.
     */
    public Builder setDownlinkId(int value) {

      downlinkId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Downlink ID.
     * </pre>
     *
     * <code>uint32 downlink_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDownlinkId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      downlinkId_ = 0;
      onChanged();
      return this;
    }

    private Object gatewayId_ = "";
    /**
     * <pre>
     * Gateway ID (EUI64).
     * </pre>
     *
     * <code>string gateway_id = 5;</code>
     * @return The gatewayId.
     */
    public String getGatewayId() {
      Object ref = gatewayId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        gatewayId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Gateway ID (EUI64).
     * </pre>
     *
     * <code>string gateway_id = 5;</code>
     * @return The bytes for gatewayId.
     */
    public com.google.protobuf.ByteString
        getGatewayIdBytes() {
      Object ref = gatewayId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        gatewayId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Gateway ID (EUI64).
     * </pre>
     *
     * <code>string gateway_id = 5;</code>
     * @param value The gatewayId to set.
     * @return This builder for chaining.
     */
    public Builder setGatewayId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      gatewayId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Gateway ID (EUI64).
     * </pre>
     *
     * <code>string gateway_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearGatewayId() {
      gatewayId_ = getDefaultInstance().getGatewayId();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Gateway ID (EUI64).
     * </pre>
     *
     * <code>string gateway_id = 5;</code>
     * @param value The bytes for gatewayId to set.
     * @return This builder for chaining.
     */
    public Builder setGatewayIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      gatewayId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private int mType_ = 0;
    /**
     * <pre>
     * Message type.
     * </pre>
     *
     * <code>.common.MType m_type = 6;</code>
     * @return The enum numeric value on the wire for mType.
     */
    @Override public int getMTypeValue() {
      return mType_;
    }
    /**
     * <pre>
     * Message type.
     * </pre>
     *
     * <code>.common.MType m_type = 6;</code>
     * @param value The enum numeric value on the wire for mType to set.
     * @return This builder for chaining.
     */
    public Builder setMTypeValue(int value) {
      mType_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Message type.
     * </pre>
     *
     * <code>.common.MType m_type = 6;</code>
     * @return The mType.
     */
    @Override
    public io.chirpstack.api.MType getMType() {
      io.chirpstack.api.MType result = io.chirpstack.api.MType.forNumber(mType_);
      return result == null ? io.chirpstack.api.MType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Message type.
     * </pre>
     *
     * <code>.common.MType m_type = 6;</code>
     * @param value The mType to set.
     * @return This builder for chaining.
     */
    public Builder setMType(io.chirpstack.api.MType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000020;
      mType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Message type.
     * </pre>
     *
     * <code>.common.MType m_type = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMType() {
      bitField0_ = (bitField0_ & ~0x00000020);
      mType_ = 0;
      onChanged();
      return this;
    }

    private Object devAddr_ = "";
    /**
     * <pre>
     * Device address (optional).
     * </pre>
     *
     * <code>string dev_addr = 7;</code>
     * @return The devAddr.
     */
    public String getDevAddr() {
      Object ref = devAddr_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        devAddr_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Device address (optional).
     * </pre>
     *
     * <code>string dev_addr = 7;</code>
     * @return The bytes for devAddr.
     */
    public com.google.protobuf.ByteString
        getDevAddrBytes() {
      Object ref = devAddr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        devAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Device address (optional).
     * </pre>
     *
     * <code>string dev_addr = 7;</code>
     * @param value The devAddr to set.
     * @return This builder for chaining.
     */
    public Builder setDevAddr(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      devAddr_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Device address (optional).
     * </pre>
     *
     * <code>string dev_addr = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDevAddr() {
      devAddr_ = getDefaultInstance().getDevAddr();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Device address (optional).
     * </pre>
     *
     * <code>string dev_addr = 7;</code>
     * @param value The bytes for devAddr to set.
     * @return This builder for chaining.
     */
    public Builder setDevAddrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      devAddr_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private Object devEui_ = "";
    /**
     * <pre>
     * Device EUI (optional).
     * </pre>
     *
     * <code>string dev_eui = 8;</code>
     * @return The devEui.
     */
    public String getDevEui() {
      Object ref = devEui_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        devEui_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Device EUI (optional).
     * </pre>
     *
     * <code>string dev_eui = 8;</code>
     * @return The bytes for devEui.
     */
    public com.google.protobuf.ByteString
        getDevEuiBytes() {
      Object ref = devEui_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        devEui_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Device EUI (optional).
     * </pre>
     *
     * <code>string dev_eui = 8;</code>
     * @param value The devEui to set.
     * @return This builder for chaining.
     */
    public Builder setDevEui(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      devEui_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Device EUI (optional).
     * </pre>
     *
     * <code>string dev_eui = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDevEui() {
      devEui_ = getDefaultInstance().getDevEui();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Device EUI (optional).
     * </pre>
     *
     * <code>string dev_eui = 8;</code>
     * @param value The bytes for devEui to set.
     * @return This builder for chaining.
     */
    public Builder setDevEuiBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      devEui_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private boolean plaintextMacCommands_ ;
    /**
     * <pre>
     * Plaintext mac-commands.
     * </pre>
     *
     * <code>bool plaintext_mac_commands = 9;</code>
     * @return The plaintextMacCommands.
     */
    @Override
    public boolean getPlaintextMacCommands() {
      return plaintextMacCommands_;
    }
    /**
     * <pre>
     * Plaintext mac-commands.
     * </pre>
     *
     * <code>bool plaintext_mac_commands = 9;</code>
     * @param value The plaintextMacCommands to set.
     * @return This builder for chaining.
     */
    public Builder setPlaintextMacCommands(boolean value) {

      plaintextMacCommands_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Plaintext mac-commands.
     * </pre>
     *
     * <code>bool plaintext_mac_commands = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlaintextMacCommands() {
      bitField0_ = (bitField0_ & ~0x00000100);
      plaintextMacCommands_ = false;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.DownlinkFrameLog)
  }

  // @@protoc_insertion_point(class_scope:api.DownlinkFrameLog)
  private static final DownlinkFrameLog DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DownlinkFrameLog();
  }

  public static DownlinkFrameLog getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DownlinkFrameLog>
      PARSER = new com.google.protobuf.AbstractParser<DownlinkFrameLog>() {
    @Override
    public DownlinkFrameLog parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DownlinkFrameLog> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<DownlinkFrameLog> getParserForType() {
    return PARSER;
  }

  @Override
  public DownlinkFrameLog getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

