// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/device.proto
// Protobuf Java Version: 4.29.2

package io.chirpstack.api;

public interface GetDeviceNextFCntDownResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.GetDeviceNextFCntDownResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * FCntDown.
   * </pre>
   *
   * <code>uint32 f_cnt_down = 1;</code>
   * @return The fCntDown.
   */
  int getFCntDown();
}
