// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/device.proto

package io.chirpstack.api;

/**
 * Protobuf type {@code api.GetDeviceLinkMetricsResponse}
 */
public final class GetDeviceLinkMetricsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.GetDeviceLinkMetricsResponse)
    GetDeviceLinkMetricsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetDeviceLinkMetricsResponse.newBuilder() to construct.
  private GetDeviceLinkMetricsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetDeviceLinkMetricsResponse() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetDeviceLinkMetricsResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return DeviceProto.internal_static_api_GetDeviceLinkMetricsResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return DeviceProto.internal_static_api_GetDeviceLinkMetricsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GetDeviceLinkMetricsResponse.class, Builder.class);
  }

  public static final int RX_PACKETS_FIELD_NUMBER = 1;
  private io.chirpstack.api.Metric rxPackets_;
  /**
   * <pre>
   * Packets received from the device.
   * </pre>
   *
   * <code>.common.Metric rx_packets = 1;</code>
   * @return Whether the rxPackets field is set.
   */
  @Override
  public boolean hasRxPackets() {
    return rxPackets_ != null;
  }
  /**
   * <pre>
   * Packets received from the device.
   * </pre>
   *
   * <code>.common.Metric rx_packets = 1;</code>
   * @return The rxPackets.
   */
  @Override
  public io.chirpstack.api.Metric getRxPackets() {
    return rxPackets_ == null ? io.chirpstack.api.Metric.getDefaultInstance() : rxPackets_;
  }
  /**
   * <pre>
   * Packets received from the device.
   * </pre>
   *
   * <code>.common.Metric rx_packets = 1;</code>
   */
  @Override
  public io.chirpstack.api.MetricOrBuilder getRxPacketsOrBuilder() {
    return rxPackets_ == null ? io.chirpstack.api.Metric.getDefaultInstance() : rxPackets_;
  }

  public static final int GW_RSSI_FIELD_NUMBER = 2;
  private io.chirpstack.api.Metric gwRssi_;
  /**
   * <pre>
   * RSSI (as reported by the gateway(s)).
   * </pre>
   *
   * <code>.common.Metric gw_rssi = 2;</code>
   * @return Whether the gwRssi field is set.
   */
  @Override
  public boolean hasGwRssi() {
    return gwRssi_ != null;
  }
  /**
   * <pre>
   * RSSI (as reported by the gateway(s)).
   * </pre>
   *
   * <code>.common.Metric gw_rssi = 2;</code>
   * @return The gwRssi.
   */
  @Override
  public io.chirpstack.api.Metric getGwRssi() {
    return gwRssi_ == null ? io.chirpstack.api.Metric.getDefaultInstance() : gwRssi_;
  }
  /**
   * <pre>
   * RSSI (as reported by the gateway(s)).
   * </pre>
   *
   * <code>.common.Metric gw_rssi = 2;</code>
   */
  @Override
  public io.chirpstack.api.MetricOrBuilder getGwRssiOrBuilder() {
    return gwRssi_ == null ? io.chirpstack.api.Metric.getDefaultInstance() : gwRssi_;
  }

  public static final int GW_SNR_FIELD_NUMBER = 3;
  private io.chirpstack.api.Metric gwSnr_;
  /**
   * <pre>
   * SNR (as reported by the gateway(s)).
   * </pre>
   *
   * <code>.common.Metric gw_snr = 3;</code>
   * @return Whether the gwSnr field is set.
   */
  @Override
  public boolean hasGwSnr() {
    return gwSnr_ != null;
  }
  /**
   * <pre>
   * SNR (as reported by the gateway(s)).
   * </pre>
   *
   * <code>.common.Metric gw_snr = 3;</code>
   * @return The gwSnr.
   */
  @Override
  public io.chirpstack.api.Metric getGwSnr() {
    return gwSnr_ == null ? io.chirpstack.api.Metric.getDefaultInstance() : gwSnr_;
  }
  /**
   * <pre>
   * SNR (as reported by the gateway(s)).
   * </pre>
   *
   * <code>.common.Metric gw_snr = 3;</code>
   */
  @Override
  public io.chirpstack.api.MetricOrBuilder getGwSnrOrBuilder() {
    return gwSnr_ == null ? io.chirpstack.api.Metric.getDefaultInstance() : gwSnr_;
  }

  public static final int RX_PACKETS_PER_FREQ_FIELD_NUMBER = 4;
  private io.chirpstack.api.Metric rxPacketsPerFreq_;
  /**
   * <pre>
   * Packets received by frequency.
   * </pre>
   *
   * <code>.common.Metric rx_packets_per_freq = 4;</code>
   * @return Whether the rxPacketsPerFreq field is set.
   */
  @Override
  public boolean hasRxPacketsPerFreq() {
    return rxPacketsPerFreq_ != null;
  }
  /**
   * <pre>
   * Packets received by frequency.
   * </pre>
   *
   * <code>.common.Metric rx_packets_per_freq = 4;</code>
   * @return The rxPacketsPerFreq.
   */
  @Override
  public io.chirpstack.api.Metric getRxPacketsPerFreq() {
    return rxPacketsPerFreq_ == null ? io.chirpstack.api.Metric.getDefaultInstance() : rxPacketsPerFreq_;
  }
  /**
   * <pre>
   * Packets received by frequency.
   * </pre>
   *
   * <code>.common.Metric rx_packets_per_freq = 4;</code>
   */
  @Override
  public io.chirpstack.api.MetricOrBuilder getRxPacketsPerFreqOrBuilder() {
    return rxPacketsPerFreq_ == null ? io.chirpstack.api.Metric.getDefaultInstance() : rxPacketsPerFreq_;
  }

  public static final int RX_PACKETS_PER_DR_FIELD_NUMBER = 5;
  private io.chirpstack.api.Metric rxPacketsPerDr_;
  /**
   * <pre>
   * Packets received by DR.
   * </pre>
   *
   * <code>.common.Metric rx_packets_per_dr = 5;</code>
   * @return Whether the rxPacketsPerDr field is set.
   */
  @Override
  public boolean hasRxPacketsPerDr() {
    return rxPacketsPerDr_ != null;
  }
  /**
   * <pre>
   * Packets received by DR.
   * </pre>
   *
   * <code>.common.Metric rx_packets_per_dr = 5;</code>
   * @return The rxPacketsPerDr.
   */
  @Override
  public io.chirpstack.api.Metric getRxPacketsPerDr() {
    return rxPacketsPerDr_ == null ? io.chirpstack.api.Metric.getDefaultInstance() : rxPacketsPerDr_;
  }
  /**
   * <pre>
   * Packets received by DR.
   * </pre>
   *
   * <code>.common.Metric rx_packets_per_dr = 5;</code>
   */
  @Override
  public io.chirpstack.api.MetricOrBuilder getRxPacketsPerDrOrBuilder() {
    return rxPacketsPerDr_ == null ? io.chirpstack.api.Metric.getDefaultInstance() : rxPacketsPerDr_;
  }

  public static final int ERRORS_FIELD_NUMBER = 6;
  private io.chirpstack.api.Metric errors_;
  /**
   * <pre>
   * Errors.
   * </pre>
   *
   * <code>.common.Metric errors = 6;</code>
   * @return Whether the errors field is set.
   */
  @Override
  public boolean hasErrors() {
    return errors_ != null;
  }
  /**
   * <pre>
   * Errors.
   * </pre>
   *
   * <code>.common.Metric errors = 6;</code>
   * @return The errors.
   */
  @Override
  public io.chirpstack.api.Metric getErrors() {
    return errors_ == null ? io.chirpstack.api.Metric.getDefaultInstance() : errors_;
  }
  /**
   * <pre>
   * Errors.
   * </pre>
   *
   * <code>.common.Metric errors = 6;</code>
   */
  @Override
  public io.chirpstack.api.MetricOrBuilder getErrorsOrBuilder() {
    return errors_ == null ? io.chirpstack.api.Metric.getDefaultInstance() : errors_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (rxPackets_ != null) {
      output.writeMessage(1, getRxPackets());
    }
    if (gwRssi_ != null) {
      output.writeMessage(2, getGwRssi());
    }
    if (gwSnr_ != null) {
      output.writeMessage(3, getGwSnr());
    }
    if (rxPacketsPerFreq_ != null) {
      output.writeMessage(4, getRxPacketsPerFreq());
    }
    if (rxPacketsPerDr_ != null) {
      output.writeMessage(5, getRxPacketsPerDr());
    }
    if (errors_ != null) {
      output.writeMessage(6, getErrors());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (rxPackets_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRxPackets());
    }
    if (gwRssi_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getGwRssi());
    }
    if (gwSnr_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getGwSnr());
    }
    if (rxPacketsPerFreq_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getRxPacketsPerFreq());
    }
    if (rxPacketsPerDr_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getRxPacketsPerDr());
    }
    if (errors_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getErrors());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GetDeviceLinkMetricsResponse)) {
      return super.equals(obj);
    }
    GetDeviceLinkMetricsResponse other = (GetDeviceLinkMetricsResponse) obj;

    if (hasRxPackets() != other.hasRxPackets()) return false;
    if (hasRxPackets()) {
      if (!getRxPackets()
          .equals(other.getRxPackets())) return false;
    }
    if (hasGwRssi() != other.hasGwRssi()) return false;
    if (hasGwRssi()) {
      if (!getGwRssi()
          .equals(other.getGwRssi())) return false;
    }
    if (hasGwSnr() != other.hasGwSnr()) return false;
    if (hasGwSnr()) {
      if (!getGwSnr()
          .equals(other.getGwSnr())) return false;
    }
    if (hasRxPacketsPerFreq() != other.hasRxPacketsPerFreq()) return false;
    if (hasRxPacketsPerFreq()) {
      if (!getRxPacketsPerFreq()
          .equals(other.getRxPacketsPerFreq())) return false;
    }
    if (hasRxPacketsPerDr() != other.hasRxPacketsPerDr()) return false;
    if (hasRxPacketsPerDr()) {
      if (!getRxPacketsPerDr()
          .equals(other.getRxPacketsPerDr())) return false;
    }
    if (hasErrors() != other.hasErrors()) return false;
    if (hasErrors()) {
      if (!getErrors()
          .equals(other.getErrors())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRxPackets()) {
      hash = (37 * hash) + RX_PACKETS_FIELD_NUMBER;
      hash = (53 * hash) + getRxPackets().hashCode();
    }
    if (hasGwRssi()) {
      hash = (37 * hash) + GW_RSSI_FIELD_NUMBER;
      hash = (53 * hash) + getGwRssi().hashCode();
    }
    if (hasGwSnr()) {
      hash = (37 * hash) + GW_SNR_FIELD_NUMBER;
      hash = (53 * hash) + getGwSnr().hashCode();
    }
    if (hasRxPacketsPerFreq()) {
      hash = (37 * hash) + RX_PACKETS_PER_FREQ_FIELD_NUMBER;
      hash = (53 * hash) + getRxPacketsPerFreq().hashCode();
    }
    if (hasRxPacketsPerDr()) {
      hash = (37 * hash) + RX_PACKETS_PER_DR_FIELD_NUMBER;
      hash = (53 * hash) + getRxPacketsPerDr().hashCode();
    }
    if (hasErrors()) {
      hash = (37 * hash) + ERRORS_FIELD_NUMBER;
      hash = (53 * hash) + getErrors().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GetDeviceLinkMetricsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetDeviceLinkMetricsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetDeviceLinkMetricsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetDeviceLinkMetricsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetDeviceLinkMetricsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetDeviceLinkMetricsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetDeviceLinkMetricsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetDeviceLinkMetricsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetDeviceLinkMetricsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static GetDeviceLinkMetricsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetDeviceLinkMetricsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetDeviceLinkMetricsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GetDeviceLinkMetricsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.GetDeviceLinkMetricsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.GetDeviceLinkMetricsResponse)
      GetDeviceLinkMetricsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DeviceProto.internal_static_api_GetDeviceLinkMetricsResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DeviceProto.internal_static_api_GetDeviceLinkMetricsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetDeviceLinkMetricsResponse.class, Builder.class);
    }

    // Construct using io.chirpstack.api.GetDeviceLinkMetricsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      rxPackets_ = null;
      if (rxPacketsBuilder_ != null) {
        rxPacketsBuilder_.dispose();
        rxPacketsBuilder_ = null;
      }
      gwRssi_ = null;
      if (gwRssiBuilder_ != null) {
        gwRssiBuilder_.dispose();
        gwRssiBuilder_ = null;
      }
      gwSnr_ = null;
      if (gwSnrBuilder_ != null) {
        gwSnrBuilder_.dispose();
        gwSnrBuilder_ = null;
      }
      rxPacketsPerFreq_ = null;
      if (rxPacketsPerFreqBuilder_ != null) {
        rxPacketsPerFreqBuilder_.dispose();
        rxPacketsPerFreqBuilder_ = null;
      }
      rxPacketsPerDr_ = null;
      if (rxPacketsPerDrBuilder_ != null) {
        rxPacketsPerDrBuilder_.dispose();
        rxPacketsPerDrBuilder_ = null;
      }
      errors_ = null;
      if (errorsBuilder_ != null) {
        errorsBuilder_.dispose();
        errorsBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return DeviceProto.internal_static_api_GetDeviceLinkMetricsResponse_descriptor;
    }

    @Override
    public GetDeviceLinkMetricsResponse getDefaultInstanceForType() {
      return GetDeviceLinkMetricsResponse.getDefaultInstance();
    }

    @Override
    public GetDeviceLinkMetricsResponse build() {
      GetDeviceLinkMetricsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public GetDeviceLinkMetricsResponse buildPartial() {
      GetDeviceLinkMetricsResponse result = new GetDeviceLinkMetricsResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(GetDeviceLinkMetricsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.rxPackets_ = rxPacketsBuilder_ == null
            ? rxPackets_
            : rxPacketsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.gwRssi_ = gwRssiBuilder_ == null
            ? gwRssi_
            : gwRssiBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.gwSnr_ = gwSnrBuilder_ == null
            ? gwSnr_
            : gwSnrBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.rxPacketsPerFreq_ = rxPacketsPerFreqBuilder_ == null
            ? rxPacketsPerFreq_
            : rxPacketsPerFreqBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.rxPacketsPerDr_ = rxPacketsPerDrBuilder_ == null
            ? rxPacketsPerDr_
            : rxPacketsPerDrBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.errors_ = errorsBuilder_ == null
            ? errors_
            : errorsBuilder_.build();
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GetDeviceLinkMetricsResponse) {
        return mergeFrom((GetDeviceLinkMetricsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GetDeviceLinkMetricsResponse other) {
      if (other == GetDeviceLinkMetricsResponse.getDefaultInstance()) return this;
      if (other.hasRxPackets()) {
        mergeRxPackets(other.getRxPackets());
      }
      if (other.hasGwRssi()) {
        mergeGwRssi(other.getGwRssi());
      }
      if (other.hasGwSnr()) {
        mergeGwSnr(other.getGwSnr());
      }
      if (other.hasRxPacketsPerFreq()) {
        mergeRxPacketsPerFreq(other.getRxPacketsPerFreq());
      }
      if (other.hasRxPacketsPerDr()) {
        mergeRxPacketsPerDr(other.getRxPacketsPerDr());
      }
      if (other.hasErrors()) {
        mergeErrors(other.getErrors());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getRxPacketsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getGwRssiFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getGwSnrFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getRxPacketsPerFreqFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getRxPacketsPerDrFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getErrorsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private io.chirpstack.api.Metric rxPackets_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.chirpstack.api.Metric, io.chirpstack.api.Metric.Builder, io.chirpstack.api.MetricOrBuilder> rxPacketsBuilder_;
    /**
     * <pre>
     * Packets received from the device.
     * </pre>
     *
     * <code>.common.Metric rx_packets = 1;</code>
     * @return Whether the rxPackets field is set.
     */
    public boolean hasRxPackets() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Packets received from the device.
     * </pre>
     *
     * <code>.common.Metric rx_packets = 1;</code>
     * @return The rxPackets.
     */
    public io.chirpstack.api.Metric getRxPackets() {
      if (rxPacketsBuilder_ == null) {
        return rxPackets_ == null ? io.chirpstack.api.Metric.getDefaultInstance() : rxPackets_;
      } else {
        return rxPacketsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Packets received from the device.
     * </pre>
     *
     * <code>.common.Metric rx_packets = 1;</code>
     */
    public Builder setRxPackets(io.chirpstack.api.Metric value) {
      if (rxPacketsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rxPackets_ = value;
      } else {
        rxPacketsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Packets received from the device.
     * </pre>
     *
     * <code>.common.Metric rx_packets = 1;</code>
     */
    public Builder setRxPackets(
        io.chirpstack.api.Metric.Builder builderForValue) {
      if (rxPacketsBuilder_ == null) {
        rxPackets_ = builderForValue.build();
      } else {
        rxPacketsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Packets received from the device.
     * </pre>
     *
     * <code>.common.Metric rx_packets = 1;</code>
     */
    public Builder mergeRxPackets(io.chirpstack.api.Metric value) {
      if (rxPacketsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          rxPackets_ != null &&
          rxPackets_ != io.chirpstack.api.Metric.getDefaultInstance()) {
          getRxPacketsBuilder().mergeFrom(value);
        } else {
          rxPackets_ = value;
        }
      } else {
        rxPacketsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Packets received from the device.
     * </pre>
     *
     * <code>.common.Metric rx_packets = 1;</code>
     */
    public Builder clearRxPackets() {
      bitField0_ = (bitField0_ & ~0x00000001);
      rxPackets_ = null;
      if (rxPacketsBuilder_ != null) {
        rxPacketsBuilder_.dispose();
        rxPacketsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Packets received from the device.
     * </pre>
     *
     * <code>.common.Metric rx_packets = 1;</code>
     */
    public io.chirpstack.api.Metric.Builder getRxPacketsBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getRxPacketsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Packets received from the device.
     * </pre>
     *
     * <code>.common.Metric rx_packets = 1;</code>
     */
    public io.chirpstack.api.MetricOrBuilder getRxPacketsOrBuilder() {
      if (rxPacketsBuilder_ != null) {
        return rxPacketsBuilder_.getMessageOrBuilder();
      } else {
        return rxPackets_ == null ?
            io.chirpstack.api.Metric.getDefaultInstance() : rxPackets_;
      }
    }
    /**
     * <pre>
     * Packets received from the device.
     * </pre>
     *
     * <code>.common.Metric rx_packets = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.chirpstack.api.Metric, io.chirpstack.api.Metric.Builder, io.chirpstack.api.MetricOrBuilder> 
        getRxPacketsFieldBuilder() {
      if (rxPacketsBuilder_ == null) {
        rxPacketsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.chirpstack.api.Metric, io.chirpstack.api.Metric.Builder, io.chirpstack.api.MetricOrBuilder>(
                getRxPackets(),
                getParentForChildren(),
                isClean());
        rxPackets_ = null;
      }
      return rxPacketsBuilder_;
    }

    private io.chirpstack.api.Metric gwRssi_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.chirpstack.api.Metric, io.chirpstack.api.Metric.Builder, io.chirpstack.api.MetricOrBuilder> gwRssiBuilder_;
    /**
     * <pre>
     * RSSI (as reported by the gateway(s)).
     * </pre>
     *
     * <code>.common.Metric gw_rssi = 2;</code>
     * @return Whether the gwRssi field is set.
     */
    public boolean hasGwRssi() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * RSSI (as reported by the gateway(s)).
     * </pre>
     *
     * <code>.common.Metric gw_rssi = 2;</code>
     * @return The gwRssi.
     */
    public io.chirpstack.api.Metric getGwRssi() {
      if (gwRssiBuilder_ == null) {
        return gwRssi_ == null ? io.chirpstack.api.Metric.getDefaultInstance() : gwRssi_;
      } else {
        return gwRssiBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * RSSI (as reported by the gateway(s)).
     * </pre>
     *
     * <code>.common.Metric gw_rssi = 2;</code>
     */
    public Builder setGwRssi(io.chirpstack.api.Metric value) {
      if (gwRssiBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        gwRssi_ = value;
      } else {
        gwRssiBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * RSSI (as reported by the gateway(s)).
     * </pre>
     *
     * <code>.common.Metric gw_rssi = 2;</code>
     */
    public Builder setGwRssi(
        io.chirpstack.api.Metric.Builder builderForValue) {
      if (gwRssiBuilder_ == null) {
        gwRssi_ = builderForValue.build();
      } else {
        gwRssiBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * RSSI (as reported by the gateway(s)).
     * </pre>
     *
     * <code>.common.Metric gw_rssi = 2;</code>
     */
    public Builder mergeGwRssi(io.chirpstack.api.Metric value) {
      if (gwRssiBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          gwRssi_ != null &&
          gwRssi_ != io.chirpstack.api.Metric.getDefaultInstance()) {
          getGwRssiBuilder().mergeFrom(value);
        } else {
          gwRssi_ = value;
        }
      } else {
        gwRssiBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * RSSI (as reported by the gateway(s)).
     * </pre>
     *
     * <code>.common.Metric gw_rssi = 2;</code>
     */
    public Builder clearGwRssi() {
      bitField0_ = (bitField0_ & ~0x00000002);
      gwRssi_ = null;
      if (gwRssiBuilder_ != null) {
        gwRssiBuilder_.dispose();
        gwRssiBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * RSSI (as reported by the gateway(s)).
     * </pre>
     *
     * <code>.common.Metric gw_rssi = 2;</code>
     */
    public io.chirpstack.api.Metric.Builder getGwRssiBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getGwRssiFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * RSSI (as reported by the gateway(s)).
     * </pre>
     *
     * <code>.common.Metric gw_rssi = 2;</code>
     */
    public io.chirpstack.api.MetricOrBuilder getGwRssiOrBuilder() {
      if (gwRssiBuilder_ != null) {
        return gwRssiBuilder_.getMessageOrBuilder();
      } else {
        return gwRssi_ == null ?
            io.chirpstack.api.Metric.getDefaultInstance() : gwRssi_;
      }
    }
    /**
     * <pre>
     * RSSI (as reported by the gateway(s)).
     * </pre>
     *
     * <code>.common.Metric gw_rssi = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.chirpstack.api.Metric, io.chirpstack.api.Metric.Builder, io.chirpstack.api.MetricOrBuilder> 
        getGwRssiFieldBuilder() {
      if (gwRssiBuilder_ == null) {
        gwRssiBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.chirpstack.api.Metric, io.chirpstack.api.Metric.Builder, io.chirpstack.api.MetricOrBuilder>(
                getGwRssi(),
                getParentForChildren(),
                isClean());
        gwRssi_ = null;
      }
      return gwRssiBuilder_;
    }

    private io.chirpstack.api.Metric gwSnr_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.chirpstack.api.Metric, io.chirpstack.api.Metric.Builder, io.chirpstack.api.MetricOrBuilder> gwSnrBuilder_;
    /**
     * <pre>
     * SNR (as reported by the gateway(s)).
     * </pre>
     *
     * <code>.common.Metric gw_snr = 3;</code>
     * @return Whether the gwSnr field is set.
     */
    public boolean hasGwSnr() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * SNR (as reported by the gateway(s)).
     * </pre>
     *
     * <code>.common.Metric gw_snr = 3;</code>
     * @return The gwSnr.
     */
    public io.chirpstack.api.Metric getGwSnr() {
      if (gwSnrBuilder_ == null) {
        return gwSnr_ == null ? io.chirpstack.api.Metric.getDefaultInstance() : gwSnr_;
      } else {
        return gwSnrBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * SNR (as reported by the gateway(s)).
     * </pre>
     *
     * <code>.common.Metric gw_snr = 3;</code>
     */
    public Builder setGwSnr(io.chirpstack.api.Metric value) {
      if (gwSnrBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        gwSnr_ = value;
      } else {
        gwSnrBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * SNR (as reported by the gateway(s)).
     * </pre>
     *
     * <code>.common.Metric gw_snr = 3;</code>
     */
    public Builder setGwSnr(
        io.chirpstack.api.Metric.Builder builderForValue) {
      if (gwSnrBuilder_ == null) {
        gwSnr_ = builderForValue.build();
      } else {
        gwSnrBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * SNR (as reported by the gateway(s)).
     * </pre>
     *
     * <code>.common.Metric gw_snr = 3;</code>
     */
    public Builder mergeGwSnr(io.chirpstack.api.Metric value) {
      if (gwSnrBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          gwSnr_ != null &&
          gwSnr_ != io.chirpstack.api.Metric.getDefaultInstance()) {
          getGwSnrBuilder().mergeFrom(value);
        } else {
          gwSnr_ = value;
        }
      } else {
        gwSnrBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * SNR (as reported by the gateway(s)).
     * </pre>
     *
     * <code>.common.Metric gw_snr = 3;</code>
     */
    public Builder clearGwSnr() {
      bitField0_ = (bitField0_ & ~0x00000004);
      gwSnr_ = null;
      if (gwSnrBuilder_ != null) {
        gwSnrBuilder_.dispose();
        gwSnrBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * SNR (as reported by the gateway(s)).
     * </pre>
     *
     * <code>.common.Metric gw_snr = 3;</code>
     */
    public io.chirpstack.api.Metric.Builder getGwSnrBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getGwSnrFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * SNR (as reported by the gateway(s)).
     * </pre>
     *
     * <code>.common.Metric gw_snr = 3;</code>
     */
    public io.chirpstack.api.MetricOrBuilder getGwSnrOrBuilder() {
      if (gwSnrBuilder_ != null) {
        return gwSnrBuilder_.getMessageOrBuilder();
      } else {
        return gwSnr_ == null ?
            io.chirpstack.api.Metric.getDefaultInstance() : gwSnr_;
      }
    }
    /**
     * <pre>
     * SNR (as reported by the gateway(s)).
     * </pre>
     *
     * <code>.common.Metric gw_snr = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.chirpstack.api.Metric, io.chirpstack.api.Metric.Builder, io.chirpstack.api.MetricOrBuilder> 
        getGwSnrFieldBuilder() {
      if (gwSnrBuilder_ == null) {
        gwSnrBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.chirpstack.api.Metric, io.chirpstack.api.Metric.Builder, io.chirpstack.api.MetricOrBuilder>(
                getGwSnr(),
                getParentForChildren(),
                isClean());
        gwSnr_ = null;
      }
      return gwSnrBuilder_;
    }

    private io.chirpstack.api.Metric rxPacketsPerFreq_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.chirpstack.api.Metric, io.chirpstack.api.Metric.Builder, io.chirpstack.api.MetricOrBuilder> rxPacketsPerFreqBuilder_;
    /**
     * <pre>
     * Packets received by frequency.
     * </pre>
     *
     * <code>.common.Metric rx_packets_per_freq = 4;</code>
     * @return Whether the rxPacketsPerFreq field is set.
     */
    public boolean hasRxPacketsPerFreq() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Packets received by frequency.
     * </pre>
     *
     * <code>.common.Metric rx_packets_per_freq = 4;</code>
     * @return The rxPacketsPerFreq.
     */
    public io.chirpstack.api.Metric getRxPacketsPerFreq() {
      if (rxPacketsPerFreqBuilder_ == null) {
        return rxPacketsPerFreq_ == null ? io.chirpstack.api.Metric.getDefaultInstance() : rxPacketsPerFreq_;
      } else {
        return rxPacketsPerFreqBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Packets received by frequency.
     * </pre>
     *
     * <code>.common.Metric rx_packets_per_freq = 4;</code>
     */
    public Builder setRxPacketsPerFreq(io.chirpstack.api.Metric value) {
      if (rxPacketsPerFreqBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rxPacketsPerFreq_ = value;
      } else {
        rxPacketsPerFreqBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Packets received by frequency.
     * </pre>
     *
     * <code>.common.Metric rx_packets_per_freq = 4;</code>
     */
    public Builder setRxPacketsPerFreq(
        io.chirpstack.api.Metric.Builder builderForValue) {
      if (rxPacketsPerFreqBuilder_ == null) {
        rxPacketsPerFreq_ = builderForValue.build();
      } else {
        rxPacketsPerFreqBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Packets received by frequency.
     * </pre>
     *
     * <code>.common.Metric rx_packets_per_freq = 4;</code>
     */
    public Builder mergeRxPacketsPerFreq(io.chirpstack.api.Metric value) {
      if (rxPacketsPerFreqBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          rxPacketsPerFreq_ != null &&
          rxPacketsPerFreq_ != io.chirpstack.api.Metric.getDefaultInstance()) {
          getRxPacketsPerFreqBuilder().mergeFrom(value);
        } else {
          rxPacketsPerFreq_ = value;
        }
      } else {
        rxPacketsPerFreqBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Packets received by frequency.
     * </pre>
     *
     * <code>.common.Metric rx_packets_per_freq = 4;</code>
     */
    public Builder clearRxPacketsPerFreq() {
      bitField0_ = (bitField0_ & ~0x00000008);
      rxPacketsPerFreq_ = null;
      if (rxPacketsPerFreqBuilder_ != null) {
        rxPacketsPerFreqBuilder_.dispose();
        rxPacketsPerFreqBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Packets received by frequency.
     * </pre>
     *
     * <code>.common.Metric rx_packets_per_freq = 4;</code>
     */
    public io.chirpstack.api.Metric.Builder getRxPacketsPerFreqBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getRxPacketsPerFreqFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Packets received by frequency.
     * </pre>
     *
     * <code>.common.Metric rx_packets_per_freq = 4;</code>
     */
    public io.chirpstack.api.MetricOrBuilder getRxPacketsPerFreqOrBuilder() {
      if (rxPacketsPerFreqBuilder_ != null) {
        return rxPacketsPerFreqBuilder_.getMessageOrBuilder();
      } else {
        return rxPacketsPerFreq_ == null ?
            io.chirpstack.api.Metric.getDefaultInstance() : rxPacketsPerFreq_;
      }
    }
    /**
     * <pre>
     * Packets received by frequency.
     * </pre>
     *
     * <code>.common.Metric rx_packets_per_freq = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.chirpstack.api.Metric, io.chirpstack.api.Metric.Builder, io.chirpstack.api.MetricOrBuilder> 
        getRxPacketsPerFreqFieldBuilder() {
      if (rxPacketsPerFreqBuilder_ == null) {
        rxPacketsPerFreqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.chirpstack.api.Metric, io.chirpstack.api.Metric.Builder, io.chirpstack.api.MetricOrBuilder>(
                getRxPacketsPerFreq(),
                getParentForChildren(),
                isClean());
        rxPacketsPerFreq_ = null;
      }
      return rxPacketsPerFreqBuilder_;
    }

    private io.chirpstack.api.Metric rxPacketsPerDr_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.chirpstack.api.Metric, io.chirpstack.api.Metric.Builder, io.chirpstack.api.MetricOrBuilder> rxPacketsPerDrBuilder_;
    /**
     * <pre>
     * Packets received by DR.
     * </pre>
     *
     * <code>.common.Metric rx_packets_per_dr = 5;</code>
     * @return Whether the rxPacketsPerDr field is set.
     */
    public boolean hasRxPacketsPerDr() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Packets received by DR.
     * </pre>
     *
     * <code>.common.Metric rx_packets_per_dr = 5;</code>
     * @return The rxPacketsPerDr.
     */
    public io.chirpstack.api.Metric getRxPacketsPerDr() {
      if (rxPacketsPerDrBuilder_ == null) {
        return rxPacketsPerDr_ == null ? io.chirpstack.api.Metric.getDefaultInstance() : rxPacketsPerDr_;
      } else {
        return rxPacketsPerDrBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Packets received by DR.
     * </pre>
     *
     * <code>.common.Metric rx_packets_per_dr = 5;</code>
     */
    public Builder setRxPacketsPerDr(io.chirpstack.api.Metric value) {
      if (rxPacketsPerDrBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rxPacketsPerDr_ = value;
      } else {
        rxPacketsPerDrBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Packets received by DR.
     * </pre>
     *
     * <code>.common.Metric rx_packets_per_dr = 5;</code>
     */
    public Builder setRxPacketsPerDr(
        io.chirpstack.api.Metric.Builder builderForValue) {
      if (rxPacketsPerDrBuilder_ == null) {
        rxPacketsPerDr_ = builderForValue.build();
      } else {
        rxPacketsPerDrBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Packets received by DR.
     * </pre>
     *
     * <code>.common.Metric rx_packets_per_dr = 5;</code>
     */
    public Builder mergeRxPacketsPerDr(io.chirpstack.api.Metric value) {
      if (rxPacketsPerDrBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          rxPacketsPerDr_ != null &&
          rxPacketsPerDr_ != io.chirpstack.api.Metric.getDefaultInstance()) {
          getRxPacketsPerDrBuilder().mergeFrom(value);
        } else {
          rxPacketsPerDr_ = value;
        }
      } else {
        rxPacketsPerDrBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Packets received by DR.
     * </pre>
     *
     * <code>.common.Metric rx_packets_per_dr = 5;</code>
     */
    public Builder clearRxPacketsPerDr() {
      bitField0_ = (bitField0_ & ~0x00000010);
      rxPacketsPerDr_ = null;
      if (rxPacketsPerDrBuilder_ != null) {
        rxPacketsPerDrBuilder_.dispose();
        rxPacketsPerDrBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Packets received by DR.
     * </pre>
     *
     * <code>.common.Metric rx_packets_per_dr = 5;</code>
     */
    public io.chirpstack.api.Metric.Builder getRxPacketsPerDrBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getRxPacketsPerDrFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Packets received by DR.
     * </pre>
     *
     * <code>.common.Metric rx_packets_per_dr = 5;</code>
     */
    public io.chirpstack.api.MetricOrBuilder getRxPacketsPerDrOrBuilder() {
      if (rxPacketsPerDrBuilder_ != null) {
        return rxPacketsPerDrBuilder_.getMessageOrBuilder();
      } else {
        return rxPacketsPerDr_ == null ?
            io.chirpstack.api.Metric.getDefaultInstance() : rxPacketsPerDr_;
      }
    }
    /**
     * <pre>
     * Packets received by DR.
     * </pre>
     *
     * <code>.common.Metric rx_packets_per_dr = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.chirpstack.api.Metric, io.chirpstack.api.Metric.Builder, io.chirpstack.api.MetricOrBuilder> 
        getRxPacketsPerDrFieldBuilder() {
      if (rxPacketsPerDrBuilder_ == null) {
        rxPacketsPerDrBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.chirpstack.api.Metric, io.chirpstack.api.Metric.Builder, io.chirpstack.api.MetricOrBuilder>(
                getRxPacketsPerDr(),
                getParentForChildren(),
                isClean());
        rxPacketsPerDr_ = null;
      }
      return rxPacketsPerDrBuilder_;
    }

    private io.chirpstack.api.Metric errors_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.chirpstack.api.Metric, io.chirpstack.api.Metric.Builder, io.chirpstack.api.MetricOrBuilder> errorsBuilder_;
    /**
     * <pre>
     * Errors.
     * </pre>
     *
     * <code>.common.Metric errors = 6;</code>
     * @return Whether the errors field is set.
     */
    public boolean hasErrors() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * Errors.
     * </pre>
     *
     * <code>.common.Metric errors = 6;</code>
     * @return The errors.
     */
    public io.chirpstack.api.Metric getErrors() {
      if (errorsBuilder_ == null) {
        return errors_ == null ? io.chirpstack.api.Metric.getDefaultInstance() : errors_;
      } else {
        return errorsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Errors.
     * </pre>
     *
     * <code>.common.Metric errors = 6;</code>
     */
    public Builder setErrors(io.chirpstack.api.Metric value) {
      if (errorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        errors_ = value;
      } else {
        errorsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Errors.
     * </pre>
     *
     * <code>.common.Metric errors = 6;</code>
     */
    public Builder setErrors(
        io.chirpstack.api.Metric.Builder builderForValue) {
      if (errorsBuilder_ == null) {
        errors_ = builderForValue.build();
      } else {
        errorsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Errors.
     * </pre>
     *
     * <code>.common.Metric errors = 6;</code>
     */
    public Builder mergeErrors(io.chirpstack.api.Metric value) {
      if (errorsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          errors_ != null &&
          errors_ != io.chirpstack.api.Metric.getDefaultInstance()) {
          getErrorsBuilder().mergeFrom(value);
        } else {
          errors_ = value;
        }
      } else {
        errorsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Errors.
     * </pre>
     *
     * <code>.common.Metric errors = 6;</code>
     */
    public Builder clearErrors() {
      bitField0_ = (bitField0_ & ~0x00000020);
      errors_ = null;
      if (errorsBuilder_ != null) {
        errorsBuilder_.dispose();
        errorsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Errors.
     * </pre>
     *
     * <code>.common.Metric errors = 6;</code>
     */
    public io.chirpstack.api.Metric.Builder getErrorsBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getErrorsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Errors.
     * </pre>
     *
     * <code>.common.Metric errors = 6;</code>
     */
    public io.chirpstack.api.MetricOrBuilder getErrorsOrBuilder() {
      if (errorsBuilder_ != null) {
        return errorsBuilder_.getMessageOrBuilder();
      } else {
        return errors_ == null ?
            io.chirpstack.api.Metric.getDefaultInstance() : errors_;
      }
    }
    /**
     * <pre>
     * Errors.
     * </pre>
     *
     * <code>.common.Metric errors = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.chirpstack.api.Metric, io.chirpstack.api.Metric.Builder, io.chirpstack.api.MetricOrBuilder> 
        getErrorsFieldBuilder() {
      if (errorsBuilder_ == null) {
        errorsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.chirpstack.api.Metric, io.chirpstack.api.Metric.Builder, io.chirpstack.api.MetricOrBuilder>(
                getErrors(),
                getParentForChildren(),
                isClean());
        errors_ = null;
      }
      return errorsBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.GetDeviceLinkMetricsResponse)
  }

  // @@protoc_insertion_point(class_scope:api.GetDeviceLinkMetricsResponse)
  private static final GetDeviceLinkMetricsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GetDeviceLinkMetricsResponse();
  }

  public static GetDeviceLinkMetricsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetDeviceLinkMetricsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetDeviceLinkMetricsResponse>() {
    @Override
    public GetDeviceLinkMetricsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetDeviceLinkMetricsResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<GetDeviceLinkMetricsResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public GetDeviceLinkMetricsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

