// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/internal.proto
// Protobuf Java Version: 4.29.2

package io.chirpstack.api;

public interface ListRegionsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.ListRegionsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Configured regions.
   * </pre>
   *
   * <code>repeated .api.RegionListItem regions = 1;</code>
   */
  java.util.List<io.chirpstack.api.RegionListItem> 
      getRegionsList();
  /**
   * <pre>
   * Configured regions.
   * </pre>
   *
   * <code>repeated .api.RegionListItem regions = 1;</code>
   */
  io.chirpstack.api.RegionListItem getRegions(int index);
  /**
   * <pre>
   * Configured regions.
   * </pre>
   *
   * <code>repeated .api.RegionListItem regions = 1;</code>
   */
  int getRegionsCount();
  /**
   * <pre>
   * Configured regions.
   * </pre>
   *
   * <code>repeated .api.RegionListItem regions = 1;</code>
   */
  java.util.List<? extends io.chirpstack.api.RegionListItemOrBuilder> 
      getRegionsOrBuilderList();
  /**
   * <pre>
   * Configured regions.
   * </pre>
   *
   * <code>repeated .api.RegionListItem regions = 1;</code>
   */
  io.chirpstack.api.RegionListItemOrBuilder getRegionsOrBuilder(
      int index);
}
