// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/common.proto

package io.chirpstack.api;

public interface MetricOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.Metric)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Name.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <pre>
   * Name.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Timestamps.
   * </pre>
   *
   * <code>repeated .google.protobuf.Timestamp timestamps = 2;</code>
   */
  java.util.List<com.google.protobuf.Timestamp> 
      getTimestampsList();
  /**
   * <pre>
   * Timestamps.
   * </pre>
   *
   * <code>repeated .google.protobuf.Timestamp timestamps = 2;</code>
   */
  com.google.protobuf.Timestamp getTimestamps(int index);
  /**
   * <pre>
   * Timestamps.
   * </pre>
   *
   * <code>repeated .google.protobuf.Timestamp timestamps = 2;</code>
   */
  int getTimestampsCount();
  /**
   * <pre>
   * Timestamps.
   * </pre>
   *
   * <code>repeated .google.protobuf.Timestamp timestamps = 2;</code>
   */
  java.util.List<? extends com.google.protobuf.TimestampOrBuilder> 
      getTimestampsOrBuilderList();
  /**
   * <pre>
   * Timestamps.
   * </pre>
   *
   * <code>repeated .google.protobuf.Timestamp timestamps = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampsOrBuilder(
      int index);

  /**
   * <pre>
   * Datasets.
   * </pre>
   *
   * <code>repeated .common.MetricDataset datasets = 3;</code>
   */
  java.util.List<MetricDataset>
      getDatasetsList();
  /**
   * <pre>
   * Datasets.
   * </pre>
   *
   * <code>repeated .common.MetricDataset datasets = 3;</code>
   */
  MetricDataset getDatasets(int index);
  /**
   * <pre>
   * Datasets.
   * </pre>
   *
   * <code>repeated .common.MetricDataset datasets = 3;</code>
   */
  int getDatasetsCount();
  /**
   * <pre>
   * Datasets.
   * </pre>
   *
   * <code>repeated .common.MetricDataset datasets = 3;</code>
   */
  java.util.List<? extends MetricDatasetOrBuilder>
      getDatasetsOrBuilderList();
  /**
   * <pre>
   * Datasets.
   * </pre>
   *
   * <code>repeated .common.MetricDataset datasets = 3;</code>
   */
  MetricDatasetOrBuilder getDatasetsOrBuilder(
      int index);

  /**
   * <pre>
   * Kind.
   * </pre>
   *
   * <code>.common.MetricKind kind = 4;</code>
   * @return The enum numeric value on the wire for kind.
   */
  int getKindValue();
  /**
   * <pre>
   * Kind.
   * </pre>
   *
   * <code>.common.MetricKind kind = 4;</code>
   * @return The kind.
   */
  MetricKind getKind();
}
