// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/internal.proto

// Protobuf Java Version: 3.25.1
package io.chirpstack.api;

public interface StreamDeviceFramesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.StreamDeviceFramesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Device EUI.
   * </pre>
   *
   * <code>string dev_eui = 1;</code>
   * @return The devEui.
   */
  java.lang.String getDevEui();
  /**
   * <pre>
   * Device EUI.
   * </pre>
   *
   * <code>string dev_eui = 1;</code>
   * @return The bytes for devEui.
   */
  com.google.protobuf.ByteString
      getDevEuiBytes();
}
