// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/internal.proto

package io.chirpstack.restapi;

public interface ListApiKeysResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.ListApiKeysResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Total number of API keys.
   * </pre>
   *
   * <code>uint32 total_count = 1;</code>
   * @return The totalCount.
   */
  int getTotalCount();

  /**
   * <code>repeated .api.ApiKey result = 2;</code>
   */
  java.util.List<io.chirpstack.restapi.ApiKey> 
      getResultList();
  /**
   * <code>repeated .api.ApiKey result = 2;</code>
   */
  io.chirpstack.restapi.ApiKey getResult(int index);
  /**
   * <code>repeated .api.ApiKey result = 2;</code>
   */
  int getResultCount();
  /**
   * <code>repeated .api.ApiKey result = 2;</code>
   */
  java.util.List<? extends io.chirpstack.restapi.ApiKeyOrBuilder> 
      getResultOrBuilderList();
  /**
   * <code>repeated .api.ApiKey result = 2;</code>
   */
  io.chirpstack.restapi.ApiKeyOrBuilder getResultOrBuilder(
      int index);
}
