// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gw/gw.proto
// Protobuf Java Version: 4.29.2

package io.chirpstack.api.gw;

/**
 * Protobuf type {@code gw.DownlinkTxInfo}
 */
public final class DownlinkTxInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:gw.DownlinkTxInfo)
    DownlinkTxInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      DownlinkTxInfo.class.getName());
  }
  // Use DownlinkTxInfo.newBuilder() to construct.
  private DownlinkTxInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DownlinkTxInfo() {
    context_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.chirpstack.api.gw.GatewayProto.internal_static_gw_DownlinkTxInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.chirpstack.api.gw.GatewayProto.internal_static_gw_DownlinkTxInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.chirpstack.api.gw.DownlinkTxInfo.class, io.chirpstack.api.gw.DownlinkTxInfo.Builder.class);
  }

  private int bitField0_;
  public static final int FREQUENCY_FIELD_NUMBER = 1;
  private int frequency_ = 0;
  /**
   * <pre>
   * TX frequency (in Hz).
   * </pre>
   *
   * <code>uint32 frequency = 1;</code>
   * @return The frequency.
   */
  @java.lang.Override
  public int getFrequency() {
    return frequency_;
  }

  public static final int POWER_FIELD_NUMBER = 2;
  private int power_ = 0;
  /**
   * <pre>
   * TX power (in dBm EIRP).
   * </pre>
   *
   * <code>int32 power = 2;</code>
   * @return The power.
   */
  @java.lang.Override
  public int getPower() {
    return power_;
  }

  public static final int MODULATION_FIELD_NUMBER = 3;
  private io.chirpstack.api.gw.Modulation modulation_;
  /**
   * <pre>
   * Modulation.
   * </pre>
   *
   * <code>.gw.Modulation modulation = 3;</code>
   * @return Whether the modulation field is set.
   */
  @java.lang.Override
  public boolean hasModulation() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Modulation.
   * </pre>
   *
   * <code>.gw.Modulation modulation = 3;</code>
   * @return The modulation.
   */
  @java.lang.Override
  public io.chirpstack.api.gw.Modulation getModulation() {
    return modulation_ == null ? io.chirpstack.api.gw.Modulation.getDefaultInstance() : modulation_;
  }
  /**
   * <pre>
   * Modulation.
   * </pre>
   *
   * <code>.gw.Modulation modulation = 3;</code>
   */
  @java.lang.Override
  public io.chirpstack.api.gw.ModulationOrBuilder getModulationOrBuilder() {
    return modulation_ == null ? io.chirpstack.api.gw.Modulation.getDefaultInstance() : modulation_;
  }

  public static final int BOARD_FIELD_NUMBER = 4;
  private int board_ = 0;
  /**
   * <pre>
   * The board identifier for emitting the frame.
   * </pre>
   *
   * <code>uint32 board = 4;</code>
   * @return The board.
   */
  @java.lang.Override
  public int getBoard() {
    return board_;
  }

  public static final int ANTENNA_FIELD_NUMBER = 5;
  private int antenna_ = 0;
  /**
   * <pre>
   * The antenna identifier for emitting the frame.
   * </pre>
   *
   * <code>uint32 antenna = 5;</code>
   * @return The antenna.
   */
  @java.lang.Override
  public int getAntenna() {
    return antenna_;
  }

  public static final int TIMING_FIELD_NUMBER = 6;
  private io.chirpstack.api.gw.Timing timing_;
  /**
   * <pre>
   * Timing.
   * </pre>
   *
   * <code>.gw.Timing timing = 6;</code>
   * @return Whether the timing field is set.
   */
  @java.lang.Override
  public boolean hasTiming() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Timing.
   * </pre>
   *
   * <code>.gw.Timing timing = 6;</code>
   * @return The timing.
   */
  @java.lang.Override
  public io.chirpstack.api.gw.Timing getTiming() {
    return timing_ == null ? io.chirpstack.api.gw.Timing.getDefaultInstance() : timing_;
  }
  /**
   * <pre>
   * Timing.
   * </pre>
   *
   * <code>.gw.Timing timing = 6;</code>
   */
  @java.lang.Override
  public io.chirpstack.api.gw.TimingOrBuilder getTimingOrBuilder() {
    return timing_ == null ? io.chirpstack.api.gw.Timing.getDefaultInstance() : timing_;
  }

  public static final int CONTEXT_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString context_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Gateway specific context.
   * In case of a Class-A downlink, this contains a copy of the uplink context.
   * </pre>
   *
   * <code>bytes context = 7;</code>
   * @return The context.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getContext() {
    return context_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (frequency_ != 0) {
      output.writeUInt32(1, frequency_);
    }
    if (power_ != 0) {
      output.writeInt32(2, power_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getModulation());
    }
    if (board_ != 0) {
      output.writeUInt32(4, board_);
    }
    if (antenna_ != 0) {
      output.writeUInt32(5, antenna_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(6, getTiming());
    }
    if (!context_.isEmpty()) {
      output.writeBytes(7, context_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (frequency_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, frequency_);
    }
    if (power_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, power_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getModulation());
    }
    if (board_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, board_);
    }
    if (antenna_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, antenna_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getTiming());
    }
    if (!context_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, context_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.chirpstack.api.gw.DownlinkTxInfo)) {
      return super.equals(obj);
    }
    io.chirpstack.api.gw.DownlinkTxInfo other = (io.chirpstack.api.gw.DownlinkTxInfo) obj;

    if (getFrequency()
        != other.getFrequency()) return false;
    if (getPower()
        != other.getPower()) return false;
    if (hasModulation() != other.hasModulation()) return false;
    if (hasModulation()) {
      if (!getModulation()
          .equals(other.getModulation())) return false;
    }
    if (getBoard()
        != other.getBoard()) return false;
    if (getAntenna()
        != other.getAntenna()) return false;
    if (hasTiming() != other.hasTiming()) return false;
    if (hasTiming()) {
      if (!getTiming()
          .equals(other.getTiming())) return false;
    }
    if (!getContext()
        .equals(other.getContext())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FREQUENCY_FIELD_NUMBER;
    hash = (53 * hash) + getFrequency();
    hash = (37 * hash) + POWER_FIELD_NUMBER;
    hash = (53 * hash) + getPower();
    if (hasModulation()) {
      hash = (37 * hash) + MODULATION_FIELD_NUMBER;
      hash = (53 * hash) + getModulation().hashCode();
    }
    hash = (37 * hash) + BOARD_FIELD_NUMBER;
    hash = (53 * hash) + getBoard();
    hash = (37 * hash) + ANTENNA_FIELD_NUMBER;
    hash = (53 * hash) + getAntenna();
    if (hasTiming()) {
      hash = (37 * hash) + TIMING_FIELD_NUMBER;
      hash = (53 * hash) + getTiming().hashCode();
    }
    hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
    hash = (53 * hash) + getContext().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.chirpstack.api.gw.DownlinkTxInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.chirpstack.api.gw.DownlinkTxInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.chirpstack.api.gw.DownlinkTxInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.chirpstack.api.gw.DownlinkTxInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.chirpstack.api.gw.DownlinkTxInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.chirpstack.api.gw.DownlinkTxInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.chirpstack.api.gw.DownlinkTxInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.chirpstack.api.gw.DownlinkTxInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.chirpstack.api.gw.DownlinkTxInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.chirpstack.api.gw.DownlinkTxInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.chirpstack.api.gw.DownlinkTxInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.chirpstack.api.gw.DownlinkTxInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.chirpstack.api.gw.DownlinkTxInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gw.DownlinkTxInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gw.DownlinkTxInfo)
      io.chirpstack.api.gw.DownlinkTxInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.chirpstack.api.gw.GatewayProto.internal_static_gw_DownlinkTxInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.chirpstack.api.gw.GatewayProto.internal_static_gw_DownlinkTxInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.chirpstack.api.gw.DownlinkTxInfo.class, io.chirpstack.api.gw.DownlinkTxInfo.Builder.class);
    }

    // Construct using io.chirpstack.api.gw.DownlinkTxInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getModulationFieldBuilder();
        getTimingFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      frequency_ = 0;
      power_ = 0;
      modulation_ = null;
      if (modulationBuilder_ != null) {
        modulationBuilder_.dispose();
        modulationBuilder_ = null;
      }
      board_ = 0;
      antenna_ = 0;
      timing_ = null;
      if (timingBuilder_ != null) {
        timingBuilder_.dispose();
        timingBuilder_ = null;
      }
      context_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.chirpstack.api.gw.GatewayProto.internal_static_gw_DownlinkTxInfo_descriptor;
    }

    @java.lang.Override
    public io.chirpstack.api.gw.DownlinkTxInfo getDefaultInstanceForType() {
      return io.chirpstack.api.gw.DownlinkTxInfo.getDefaultInstance();
    }

    @java.lang.Override
    public io.chirpstack.api.gw.DownlinkTxInfo build() {
      io.chirpstack.api.gw.DownlinkTxInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.chirpstack.api.gw.DownlinkTxInfo buildPartial() {
      io.chirpstack.api.gw.DownlinkTxInfo result = new io.chirpstack.api.gw.DownlinkTxInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.chirpstack.api.gw.DownlinkTxInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.frequency_ = frequency_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.power_ = power_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.modulation_ = modulationBuilder_ == null
            ? modulation_
            : modulationBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.board_ = board_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.antenna_ = antenna_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.timing_ = timingBuilder_ == null
            ? timing_
            : timingBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.context_ = context_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.chirpstack.api.gw.DownlinkTxInfo) {
        return mergeFrom((io.chirpstack.api.gw.DownlinkTxInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.chirpstack.api.gw.DownlinkTxInfo other) {
      if (other == io.chirpstack.api.gw.DownlinkTxInfo.getDefaultInstance()) return this;
      if (other.getFrequency() != 0) {
        setFrequency(other.getFrequency());
      }
      if (other.getPower() != 0) {
        setPower(other.getPower());
      }
      if (other.hasModulation()) {
        mergeModulation(other.getModulation());
      }
      if (other.getBoard() != 0) {
        setBoard(other.getBoard());
      }
      if (other.getAntenna() != 0) {
        setAntenna(other.getAntenna());
      }
      if (other.hasTiming()) {
        mergeTiming(other.getTiming());
      }
      if (other.getContext() != com.google.protobuf.ByteString.EMPTY) {
        setContext(other.getContext());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              frequency_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              power_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getModulationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              board_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              antenna_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              input.readMessage(
                  getTimingFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              context_ = input.readBytes();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int frequency_ ;
    /**
     * <pre>
     * TX frequency (in Hz).
     * </pre>
     *
     * <code>uint32 frequency = 1;</code>
     * @return The frequency.
     */
    @java.lang.Override
    public int getFrequency() {
      return frequency_;
    }
    /**
     * <pre>
     * TX frequency (in Hz).
     * </pre>
     *
     * <code>uint32 frequency = 1;</code>
     * @param value The frequency to set.
     * @return This builder for chaining.
     */
    public Builder setFrequency(int value) {

      frequency_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * TX frequency (in Hz).
     * </pre>
     *
     * <code>uint32 frequency = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrequency() {
      bitField0_ = (bitField0_ & ~0x00000001);
      frequency_ = 0;
      onChanged();
      return this;
    }

    private int power_ ;
    /**
     * <pre>
     * TX power (in dBm EIRP).
     * </pre>
     *
     * <code>int32 power = 2;</code>
     * @return The power.
     */
    @java.lang.Override
    public int getPower() {
      return power_;
    }
    /**
     * <pre>
     * TX power (in dBm EIRP).
     * </pre>
     *
     * <code>int32 power = 2;</code>
     * @param value The power to set.
     * @return This builder for chaining.
     */
    public Builder setPower(int value) {

      power_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * TX power (in dBm EIRP).
     * </pre>
     *
     * <code>int32 power = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPower() {
      bitField0_ = (bitField0_ & ~0x00000002);
      power_ = 0;
      onChanged();
      return this;
    }

    private io.chirpstack.api.gw.Modulation modulation_;
    private com.google.protobuf.SingleFieldBuilder<
        io.chirpstack.api.gw.Modulation, io.chirpstack.api.gw.Modulation.Builder, io.chirpstack.api.gw.ModulationOrBuilder> modulationBuilder_;
    /**
     * <pre>
     * Modulation.
     * </pre>
     *
     * <code>.gw.Modulation modulation = 3;</code>
     * @return Whether the modulation field is set.
     */
    public boolean hasModulation() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Modulation.
     * </pre>
     *
     * <code>.gw.Modulation modulation = 3;</code>
     * @return The modulation.
     */
    public io.chirpstack.api.gw.Modulation getModulation() {
      if (modulationBuilder_ == null) {
        return modulation_ == null ? io.chirpstack.api.gw.Modulation.getDefaultInstance() : modulation_;
      } else {
        return modulationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Modulation.
     * </pre>
     *
     * <code>.gw.Modulation modulation = 3;</code>
     */
    public Builder setModulation(io.chirpstack.api.gw.Modulation value) {
      if (modulationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        modulation_ = value;
      } else {
        modulationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Modulation.
     * </pre>
     *
     * <code>.gw.Modulation modulation = 3;</code>
     */
    public Builder setModulation(
        io.chirpstack.api.gw.Modulation.Builder builderForValue) {
      if (modulationBuilder_ == null) {
        modulation_ = builderForValue.build();
      } else {
        modulationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Modulation.
     * </pre>
     *
     * <code>.gw.Modulation modulation = 3;</code>
     */
    public Builder mergeModulation(io.chirpstack.api.gw.Modulation value) {
      if (modulationBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          modulation_ != null &&
          modulation_ != io.chirpstack.api.gw.Modulation.getDefaultInstance()) {
          getModulationBuilder().mergeFrom(value);
        } else {
          modulation_ = value;
        }
      } else {
        modulationBuilder_.mergeFrom(value);
      }
      if (modulation_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Modulation.
     * </pre>
     *
     * <code>.gw.Modulation modulation = 3;</code>
     */
    public Builder clearModulation() {
      bitField0_ = (bitField0_ & ~0x00000004);
      modulation_ = null;
      if (modulationBuilder_ != null) {
        modulationBuilder_.dispose();
        modulationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Modulation.
     * </pre>
     *
     * <code>.gw.Modulation modulation = 3;</code>
     */
    public io.chirpstack.api.gw.Modulation.Builder getModulationBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getModulationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Modulation.
     * </pre>
     *
     * <code>.gw.Modulation modulation = 3;</code>
     */
    public io.chirpstack.api.gw.ModulationOrBuilder getModulationOrBuilder() {
      if (modulationBuilder_ != null) {
        return modulationBuilder_.getMessageOrBuilder();
      } else {
        return modulation_ == null ?
            io.chirpstack.api.gw.Modulation.getDefaultInstance() : modulation_;
      }
    }
    /**
     * <pre>
     * Modulation.
     * </pre>
     *
     * <code>.gw.Modulation modulation = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.chirpstack.api.gw.Modulation, io.chirpstack.api.gw.Modulation.Builder, io.chirpstack.api.gw.ModulationOrBuilder> 
        getModulationFieldBuilder() {
      if (modulationBuilder_ == null) {
        modulationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.chirpstack.api.gw.Modulation, io.chirpstack.api.gw.Modulation.Builder, io.chirpstack.api.gw.ModulationOrBuilder>(
                getModulation(),
                getParentForChildren(),
                isClean());
        modulation_ = null;
      }
      return modulationBuilder_;
    }

    private int board_ ;
    /**
     * <pre>
     * The board identifier for emitting the frame.
     * </pre>
     *
     * <code>uint32 board = 4;</code>
     * @return The board.
     */
    @java.lang.Override
    public int getBoard() {
      return board_;
    }
    /**
     * <pre>
     * The board identifier for emitting the frame.
     * </pre>
     *
     * <code>uint32 board = 4;</code>
     * @param value The board to set.
     * @return This builder for chaining.
     */
    public Builder setBoard(int value) {

      board_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The board identifier for emitting the frame.
     * </pre>
     *
     * <code>uint32 board = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBoard() {
      bitField0_ = (bitField0_ & ~0x00000008);
      board_ = 0;
      onChanged();
      return this;
    }

    private int antenna_ ;
    /**
     * <pre>
     * The antenna identifier for emitting the frame.
     * </pre>
     *
     * <code>uint32 antenna = 5;</code>
     * @return The antenna.
     */
    @java.lang.Override
    public int getAntenna() {
      return antenna_;
    }
    /**
     * <pre>
     * The antenna identifier for emitting the frame.
     * </pre>
     *
     * <code>uint32 antenna = 5;</code>
     * @param value The antenna to set.
     * @return This builder for chaining.
     */
    public Builder setAntenna(int value) {

      antenna_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The antenna identifier for emitting the frame.
     * </pre>
     *
     * <code>uint32 antenna = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAntenna() {
      bitField0_ = (bitField0_ & ~0x00000010);
      antenna_ = 0;
      onChanged();
      return this;
    }

    private io.chirpstack.api.gw.Timing timing_;
    private com.google.protobuf.SingleFieldBuilder<
        io.chirpstack.api.gw.Timing, io.chirpstack.api.gw.Timing.Builder, io.chirpstack.api.gw.TimingOrBuilder> timingBuilder_;
    /**
     * <pre>
     * Timing.
     * </pre>
     *
     * <code>.gw.Timing timing = 6;</code>
     * @return Whether the timing field is set.
     */
    public boolean hasTiming() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * Timing.
     * </pre>
     *
     * <code>.gw.Timing timing = 6;</code>
     * @return The timing.
     */
    public io.chirpstack.api.gw.Timing getTiming() {
      if (timingBuilder_ == null) {
        return timing_ == null ? io.chirpstack.api.gw.Timing.getDefaultInstance() : timing_;
      } else {
        return timingBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Timing.
     * </pre>
     *
     * <code>.gw.Timing timing = 6;</code>
     */
    public Builder setTiming(io.chirpstack.api.gw.Timing value) {
      if (timingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timing_ = value;
      } else {
        timingBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timing.
     * </pre>
     *
     * <code>.gw.Timing timing = 6;</code>
     */
    public Builder setTiming(
        io.chirpstack.api.gw.Timing.Builder builderForValue) {
      if (timingBuilder_ == null) {
        timing_ = builderForValue.build();
      } else {
        timingBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timing.
     * </pre>
     *
     * <code>.gw.Timing timing = 6;</code>
     */
    public Builder mergeTiming(io.chirpstack.api.gw.Timing value) {
      if (timingBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          timing_ != null &&
          timing_ != io.chirpstack.api.gw.Timing.getDefaultInstance()) {
          getTimingBuilder().mergeFrom(value);
        } else {
          timing_ = value;
        }
      } else {
        timingBuilder_.mergeFrom(value);
      }
      if (timing_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Timing.
     * </pre>
     *
     * <code>.gw.Timing timing = 6;</code>
     */
    public Builder clearTiming() {
      bitField0_ = (bitField0_ & ~0x00000020);
      timing_ = null;
      if (timingBuilder_ != null) {
        timingBuilder_.dispose();
        timingBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timing.
     * </pre>
     *
     * <code>.gw.Timing timing = 6;</code>
     */
    public io.chirpstack.api.gw.Timing.Builder getTimingBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getTimingFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Timing.
     * </pre>
     *
     * <code>.gw.Timing timing = 6;</code>
     */
    public io.chirpstack.api.gw.TimingOrBuilder getTimingOrBuilder() {
      if (timingBuilder_ != null) {
        return timingBuilder_.getMessageOrBuilder();
      } else {
        return timing_ == null ?
            io.chirpstack.api.gw.Timing.getDefaultInstance() : timing_;
      }
    }
    /**
     * <pre>
     * Timing.
     * </pre>
     *
     * <code>.gw.Timing timing = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.chirpstack.api.gw.Timing, io.chirpstack.api.gw.Timing.Builder, io.chirpstack.api.gw.TimingOrBuilder> 
        getTimingFieldBuilder() {
      if (timingBuilder_ == null) {
        timingBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.chirpstack.api.gw.Timing, io.chirpstack.api.gw.Timing.Builder, io.chirpstack.api.gw.TimingOrBuilder>(
                getTiming(),
                getParentForChildren(),
                isClean());
        timing_ = null;
      }
      return timingBuilder_;
    }

    private com.google.protobuf.ByteString context_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Gateway specific context.
     * In case of a Class-A downlink, this contains a copy of the uplink context.
     * </pre>
     *
     * <code>bytes context = 7;</code>
     * @return The context.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getContext() {
      return context_;
    }
    /**
     * <pre>
     * Gateway specific context.
     * In case of a Class-A downlink, this contains a copy of the uplink context.
     * </pre>
     *
     * <code>bytes context = 7;</code>
     * @param value The context to set.
     * @return This builder for chaining.
     */
    public Builder setContext(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      context_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Gateway specific context.
     * In case of a Class-A downlink, this contains a copy of the uplink context.
     * </pre>
     *
     * <code>bytes context = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearContext() {
      bitField0_ = (bitField0_ & ~0x00000040);
      context_ = getDefaultInstance().getContext();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:gw.DownlinkTxInfo)
  }

  // @@protoc_insertion_point(class_scope:gw.DownlinkTxInfo)
  private static final io.chirpstack.api.gw.DownlinkTxInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.chirpstack.api.gw.DownlinkTxInfo();
  }

  public static io.chirpstack.api.gw.DownlinkTxInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DownlinkTxInfo>
      PARSER = new com.google.protobuf.AbstractParser<DownlinkTxInfo>() {
    @java.lang.Override
    public DownlinkTxInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DownlinkTxInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DownlinkTxInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.chirpstack.api.gw.DownlinkTxInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

