// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gw/gw.proto

// Protobuf Java Version: 3.25.1
package io.chirpstack.api.gw;

/**
 * Protobuf type {@code gw.GatewayCommandExecResponse}
 */
public final class GatewayCommandExecResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gw.GatewayCommandExecResponse)
    GatewayCommandExecResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GatewayCommandExecResponse.newBuilder() to construct.
  private GatewayCommandExecResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GatewayCommandExecResponse() {
    gatewayIdLegacy_ = com.google.protobuf.ByteString.EMPTY;
    gatewayId_ = "";
    stdout_ = com.google.protobuf.ByteString.EMPTY;
    stderr_ = com.google.protobuf.ByteString.EMPTY;
    error_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GatewayCommandExecResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.chirpstack.api.gw.GatewayProto.internal_static_gw_GatewayCommandExecResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.chirpstack.api.gw.GatewayProto.internal_static_gw_GatewayCommandExecResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.chirpstack.api.gw.GatewayCommandExecResponse.class, io.chirpstack.api.gw.GatewayCommandExecResponse.Builder.class);
  }

  public static final int GATEWAY_ID_LEGACY_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString gatewayIdLegacy_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Gateway ID.
   * Deprecated: use gateway_id.
   * </pre>
   *
   * <code>bytes gateway_id_legacy = 1;</code>
   * @return The gatewayIdLegacy.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getGatewayIdLegacy() {
    return gatewayIdLegacy_;
  }

  public static final int GATEWAY_ID_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object gatewayId_ = "";
  /**
   * <pre>
   * Gateway ID.
   * </pre>
   *
   * <code>string gateway_id = 6;</code>
   * @return The gatewayId.
   */
  @java.lang.Override
  public java.lang.String getGatewayId() {
    java.lang.Object ref = gatewayId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gatewayId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Gateway ID.
   * </pre>
   *
   * <code>string gateway_id = 6;</code>
   * @return The bytes for gatewayId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGatewayIdBytes() {
    java.lang.Object ref = gatewayId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gatewayId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXEC_ID_FIELD_NUMBER = 7;
  private int execId_ = 0;
  /**
   * <pre>
   * Execution request ID.
   * </pre>
   *
   * <code>uint32 exec_id = 7;</code>
   * @return The execId.
   */
  @java.lang.Override
  public int getExecId() {
    return execId_;
  }

  public static final int STDOUT_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString stdout_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Standard output.
   * </pre>
   *
   * <code>bytes stdout = 3;</code>
   * @return The stdout.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getStdout() {
    return stdout_;
  }

  public static final int STDERR_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString stderr_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Standard error.
   * </pre>
   *
   * <code>bytes stderr = 4;</code>
   * @return The stderr.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getStderr() {
    return stderr_;
  }

  public static final int ERROR_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object error_ = "";
  /**
   * <pre>
   * Error message.
   * </pre>
   *
   * <code>string error = 5;</code>
   * @return The error.
   */
  @java.lang.Override
  public java.lang.String getError() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      error_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Error message.
   * </pre>
   *
   * <code>string error = 5;</code>
   * @return The bytes for error.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorBytes() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      error_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!gatewayIdLegacy_.isEmpty()) {
      output.writeBytes(1, gatewayIdLegacy_);
    }
    if (!stdout_.isEmpty()) {
      output.writeBytes(3, stdout_);
    }
    if (!stderr_.isEmpty()) {
      output.writeBytes(4, stderr_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(error_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, error_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gatewayId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, gatewayId_);
    }
    if (execId_ != 0) {
      output.writeUInt32(7, execId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!gatewayIdLegacy_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, gatewayIdLegacy_);
    }
    if (!stdout_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, stdout_);
    }
    if (!stderr_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, stderr_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(error_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, error_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gatewayId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, gatewayId_);
    }
    if (execId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(7, execId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.chirpstack.api.gw.GatewayCommandExecResponse)) {
      return super.equals(obj);
    }
    io.chirpstack.api.gw.GatewayCommandExecResponse other = (io.chirpstack.api.gw.GatewayCommandExecResponse) obj;

    if (!getGatewayIdLegacy()
        .equals(other.getGatewayIdLegacy())) return false;
    if (!getGatewayId()
        .equals(other.getGatewayId())) return false;
    if (getExecId()
        != other.getExecId()) return false;
    if (!getStdout()
        .equals(other.getStdout())) return false;
    if (!getStderr()
        .equals(other.getStderr())) return false;
    if (!getError()
        .equals(other.getError())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GATEWAY_ID_LEGACY_FIELD_NUMBER;
    hash = (53 * hash) + getGatewayIdLegacy().hashCode();
    hash = (37 * hash) + GATEWAY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getGatewayId().hashCode();
    hash = (37 * hash) + EXEC_ID_FIELD_NUMBER;
    hash = (53 * hash) + getExecId();
    hash = (37 * hash) + STDOUT_FIELD_NUMBER;
    hash = (53 * hash) + getStdout().hashCode();
    hash = (37 * hash) + STDERR_FIELD_NUMBER;
    hash = (53 * hash) + getStderr().hashCode();
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.chirpstack.api.gw.GatewayCommandExecResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.chirpstack.api.gw.GatewayCommandExecResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.chirpstack.api.gw.GatewayCommandExecResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.chirpstack.api.gw.GatewayCommandExecResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.chirpstack.api.gw.GatewayCommandExecResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.chirpstack.api.gw.GatewayCommandExecResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.chirpstack.api.gw.GatewayCommandExecResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.chirpstack.api.gw.GatewayCommandExecResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.chirpstack.api.gw.GatewayCommandExecResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.chirpstack.api.gw.GatewayCommandExecResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.chirpstack.api.gw.GatewayCommandExecResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.chirpstack.api.gw.GatewayCommandExecResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.chirpstack.api.gw.GatewayCommandExecResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gw.GatewayCommandExecResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gw.GatewayCommandExecResponse)
      io.chirpstack.api.gw.GatewayCommandExecResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.chirpstack.api.gw.GatewayProto.internal_static_gw_GatewayCommandExecResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.chirpstack.api.gw.GatewayProto.internal_static_gw_GatewayCommandExecResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.chirpstack.api.gw.GatewayCommandExecResponse.class, io.chirpstack.api.gw.GatewayCommandExecResponse.Builder.class);
    }

    // Construct using io.chirpstack.api.gw.GatewayCommandExecResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      gatewayIdLegacy_ = com.google.protobuf.ByteString.EMPTY;
      gatewayId_ = "";
      execId_ = 0;
      stdout_ = com.google.protobuf.ByteString.EMPTY;
      stderr_ = com.google.protobuf.ByteString.EMPTY;
      error_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.chirpstack.api.gw.GatewayProto.internal_static_gw_GatewayCommandExecResponse_descriptor;
    }

    @java.lang.Override
    public io.chirpstack.api.gw.GatewayCommandExecResponse getDefaultInstanceForType() {
      return io.chirpstack.api.gw.GatewayCommandExecResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.chirpstack.api.gw.GatewayCommandExecResponse build() {
      io.chirpstack.api.gw.GatewayCommandExecResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.chirpstack.api.gw.GatewayCommandExecResponse buildPartial() {
      io.chirpstack.api.gw.GatewayCommandExecResponse result = new io.chirpstack.api.gw.GatewayCommandExecResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.chirpstack.api.gw.GatewayCommandExecResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.gatewayIdLegacy_ = gatewayIdLegacy_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.gatewayId_ = gatewayId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.execId_ = execId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.stdout_ = stdout_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.stderr_ = stderr_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.error_ = error_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.chirpstack.api.gw.GatewayCommandExecResponse) {
        return mergeFrom((io.chirpstack.api.gw.GatewayCommandExecResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.chirpstack.api.gw.GatewayCommandExecResponse other) {
      if (other == io.chirpstack.api.gw.GatewayCommandExecResponse.getDefaultInstance()) return this;
      if (other.getGatewayIdLegacy() != com.google.protobuf.ByteString.EMPTY) {
        setGatewayIdLegacy(other.getGatewayIdLegacy());
      }
      if (!other.getGatewayId().isEmpty()) {
        gatewayId_ = other.gatewayId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getExecId() != 0) {
        setExecId(other.getExecId());
      }
      if (other.getStdout() != com.google.protobuf.ByteString.EMPTY) {
        setStdout(other.getStdout());
      }
      if (other.getStderr() != com.google.protobuf.ByteString.EMPTY) {
        setStderr(other.getStderr());
      }
      if (!other.getError().isEmpty()) {
        error_ = other.error_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              gatewayIdLegacy_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 26: {
              stdout_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 26
            case 34: {
              stderr_ = input.readBytes();
              bitField0_ |= 0x00000010;
              break;
            } // case 34
            case 42: {
              error_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 42
            case 50: {
              gatewayId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 50
            case 56: {
              execId_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString gatewayIdLegacy_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Gateway ID.
     * Deprecated: use gateway_id.
     * </pre>
     *
     * <code>bytes gateway_id_legacy = 1;</code>
     * @return The gatewayIdLegacy.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getGatewayIdLegacy() {
      return gatewayIdLegacy_;
    }
    /**
     * <pre>
     * Gateway ID.
     * Deprecated: use gateway_id.
     * </pre>
     *
     * <code>bytes gateway_id_legacy = 1;</code>
     * @param value The gatewayIdLegacy to set.
     * @return This builder for chaining.
     */
    public Builder setGatewayIdLegacy(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      gatewayIdLegacy_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Gateway ID.
     * Deprecated: use gateway_id.
     * </pre>
     *
     * <code>bytes gateway_id_legacy = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearGatewayIdLegacy() {
      bitField0_ = (bitField0_ & ~0x00000001);
      gatewayIdLegacy_ = getDefaultInstance().getGatewayIdLegacy();
      onChanged();
      return this;
    }

    private java.lang.Object gatewayId_ = "";
    /**
     * <pre>
     * Gateway ID.
     * </pre>
     *
     * <code>string gateway_id = 6;</code>
     * @return The gatewayId.
     */
    public java.lang.String getGatewayId() {
      java.lang.Object ref = gatewayId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gatewayId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Gateway ID.
     * </pre>
     *
     * <code>string gateway_id = 6;</code>
     * @return The bytes for gatewayId.
     */
    public com.google.protobuf.ByteString
        getGatewayIdBytes() {
      java.lang.Object ref = gatewayId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gatewayId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Gateway ID.
     * </pre>
     *
     * <code>string gateway_id = 6;</code>
     * @param value The gatewayId to set.
     * @return This builder for chaining.
     */
    public Builder setGatewayId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      gatewayId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Gateway ID.
     * </pre>
     *
     * <code>string gateway_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearGatewayId() {
      gatewayId_ = getDefaultInstance().getGatewayId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Gateway ID.
     * </pre>
     *
     * <code>string gateway_id = 6;</code>
     * @param value The bytes for gatewayId to set.
     * @return This builder for chaining.
     */
    public Builder setGatewayIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      gatewayId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int execId_ ;
    /**
     * <pre>
     * Execution request ID.
     * </pre>
     *
     * <code>uint32 exec_id = 7;</code>
     * @return The execId.
     */
    @java.lang.Override
    public int getExecId() {
      return execId_;
    }
    /**
     * <pre>
     * Execution request ID.
     * </pre>
     *
     * <code>uint32 exec_id = 7;</code>
     * @param value The execId to set.
     * @return This builder for chaining.
     */
    public Builder setExecId(int value) {

      execId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Execution request ID.
     * </pre>
     *
     * <code>uint32 exec_id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearExecId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      execId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString stdout_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Standard output.
     * </pre>
     *
     * <code>bytes stdout = 3;</code>
     * @return The stdout.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getStdout() {
      return stdout_;
    }
    /**
     * <pre>
     * Standard output.
     * </pre>
     *
     * <code>bytes stdout = 3;</code>
     * @param value The stdout to set.
     * @return This builder for chaining.
     */
    public Builder setStdout(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      stdout_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Standard output.
     * </pre>
     *
     * <code>bytes stdout = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStdout() {
      bitField0_ = (bitField0_ & ~0x00000008);
      stdout_ = getDefaultInstance().getStdout();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString stderr_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Standard error.
     * </pre>
     *
     * <code>bytes stderr = 4;</code>
     * @return The stderr.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getStderr() {
      return stderr_;
    }
    /**
     * <pre>
     * Standard error.
     * </pre>
     *
     * <code>bytes stderr = 4;</code>
     * @param value The stderr to set.
     * @return This builder for chaining.
     */
    public Builder setStderr(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      stderr_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Standard error.
     * </pre>
     *
     * <code>bytes stderr = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStderr() {
      bitField0_ = (bitField0_ & ~0x00000010);
      stderr_ = getDefaultInstance().getStderr();
      onChanged();
      return this;
    }

    private java.lang.Object error_ = "";
    /**
     * <pre>
     * Error message.
     * </pre>
     *
     * <code>string error = 5;</code>
     * @return The error.
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Error message.
     * </pre>
     *
     * <code>string error = 5;</code>
     * @return The bytes for error.
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Error message.
     * </pre>
     *
     * <code>string error = 5;</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setError(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      error_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Error message.
     * </pre>
     *
     * <code>string error = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      error_ = getDefaultInstance().getError();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Error message.
     * </pre>
     *
     * <code>string error = 5;</code>
     * @param value The bytes for error to set.
     * @return This builder for chaining.
     */
    public Builder setErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      error_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gw.GatewayCommandExecResponse)
  }

  // @@protoc_insertion_point(class_scope:gw.GatewayCommandExecResponse)
  private static final io.chirpstack.api.gw.GatewayCommandExecResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.chirpstack.api.gw.GatewayCommandExecResponse();
  }

  public static io.chirpstack.api.gw.GatewayCommandExecResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GatewayCommandExecResponse>
      PARSER = new com.google.protobuf.AbstractParser<GatewayCommandExecResponse>() {
    @java.lang.Override
    public GatewayCommandExecResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GatewayCommandExecResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GatewayCommandExecResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.chirpstack.api.gw.GatewayCommandExecResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

