// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gw/gw.proto

package io.chirpstack.api.gw;

/**
 * Protobuf type {@code gw.UplinkTxInfoLegacy}
 */
public final class UplinkTxInfoLegacy extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gw.UplinkTxInfoLegacy)
    UplinkTxInfoLegacyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UplinkTxInfoLegacy.newBuilder() to construct.
  private UplinkTxInfoLegacy(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UplinkTxInfoLegacy() {
    modulation_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new UplinkTxInfoLegacy();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GatewayProto.internal_static_gw_UplinkTxInfoLegacy_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GatewayProto.internal_static_gw_UplinkTxInfoLegacy_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            UplinkTxInfoLegacy.class, Builder.class);
  }

  private int modulationInfoCase_ = 0;
  private Object modulationInfo_;
  public enum ModulationInfoCase
      implements com.google.protobuf.Internal.EnumLite,
          InternalOneOfEnum {
    LORA_MODULATION_INFO(3),
    FSK_MODULATION_INFO(4),
    LR_FHSS_MODULATION_INFO(5),
    MODULATIONINFO_NOT_SET(0);
    private final int value;
    private ModulationInfoCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ModulationInfoCase valueOf(int value) {
      return forNumber(value);
    }

    public static ModulationInfoCase forNumber(int value) {
      switch (value) {
        case 3: return LORA_MODULATION_INFO;
        case 4: return FSK_MODULATION_INFO;
        case 5: return LR_FHSS_MODULATION_INFO;
        case 0: return MODULATIONINFO_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ModulationInfoCase
  getModulationInfoCase() {
    return ModulationInfoCase.forNumber(
        modulationInfoCase_);
  }

  public static final int FREQUENCY_FIELD_NUMBER = 1;
  private int frequency_;
  /**
   * <pre>
   * Frequency (Hz).
   * </pre>
   *
   * <code>uint32 frequency = 1;</code>
   * @return The frequency.
   */
  @Override
  public int getFrequency() {
    return frequency_;
  }

  public static final int MODULATION_FIELD_NUMBER = 2;
  private int modulation_;
  /**
   * <pre>
   * Modulation.
   * </pre>
   *
   * <code>.common.Modulation modulation = 2;</code>
   * @return The enum numeric value on the wire for modulation.
   */
  @Override public int getModulationValue() {
    return modulation_;
  }
  /**
   * <pre>
   * Modulation.
   * </pre>
   *
   * <code>.common.Modulation modulation = 2;</code>
   * @return The modulation.
   */
  @Override public io.chirpstack.api.Modulation getModulation() {
    @SuppressWarnings("deprecation")
    io.chirpstack.api.Modulation result = io.chirpstack.api.Modulation.valueOf(modulation_);
    return result == null ? io.chirpstack.api.Modulation.UNRECOGNIZED : result;
  }

  public static final int LORA_MODULATION_INFO_FIELD_NUMBER = 3;
  /**
   * <pre>
   * LoRa modulation information.
   * </pre>
   *
   * <code>.gw.LoraModulationInfo lora_modulation_info = 3;</code>
   * @return Whether the loraModulationInfo field is set.
   */
  @Override
  public boolean hasLoraModulationInfo() {
    return modulationInfoCase_ == 3;
  }
  /**
   * <pre>
   * LoRa modulation information.
   * </pre>
   *
   * <code>.gw.LoraModulationInfo lora_modulation_info = 3;</code>
   * @return The loraModulationInfo.
   */
  @Override
  public LoraModulationInfo getLoraModulationInfo() {
    if (modulationInfoCase_ == 3) {
       return (LoraModulationInfo) modulationInfo_;
    }
    return LoraModulationInfo.getDefaultInstance();
  }
  /**
   * <pre>
   * LoRa modulation information.
   * </pre>
   *
   * <code>.gw.LoraModulationInfo lora_modulation_info = 3;</code>
   */
  @Override
  public LoraModulationInfoOrBuilder getLoraModulationInfoOrBuilder() {
    if (modulationInfoCase_ == 3) {
       return (LoraModulationInfo) modulationInfo_;
    }
    return LoraModulationInfo.getDefaultInstance();
  }

  public static final int FSK_MODULATION_INFO_FIELD_NUMBER = 4;
  /**
   * <pre>
   * FSK modulation information.
   * </pre>
   *
   * <code>.gw.FskModulationInfo fsk_modulation_info = 4;</code>
   * @return Whether the fskModulationInfo field is set.
   */
  @Override
  public boolean hasFskModulationInfo() {
    return modulationInfoCase_ == 4;
  }
  /**
   * <pre>
   * FSK modulation information.
   * </pre>
   *
   * <code>.gw.FskModulationInfo fsk_modulation_info = 4;</code>
   * @return The fskModulationInfo.
   */
  @Override
  public FskModulationInfo getFskModulationInfo() {
    if (modulationInfoCase_ == 4) {
       return (FskModulationInfo) modulationInfo_;
    }
    return FskModulationInfo.getDefaultInstance();
  }
  /**
   * <pre>
   * FSK modulation information.
   * </pre>
   *
   * <code>.gw.FskModulationInfo fsk_modulation_info = 4;</code>
   */
  @Override
  public FskModulationInfoOrBuilder getFskModulationInfoOrBuilder() {
    if (modulationInfoCase_ == 4) {
       return (FskModulationInfo) modulationInfo_;
    }
    return FskModulationInfo.getDefaultInstance();
  }

  public static final int LR_FHSS_MODULATION_INFO_FIELD_NUMBER = 5;
  /**
   * <pre>
   * LR-FHSS modulation information.
   * </pre>
   *
   * <code>.gw.LrFhssModulationInfo lr_fhss_modulation_info = 5;</code>
   * @return Whether the lrFhssModulationInfo field is set.
   */
  @Override
  public boolean hasLrFhssModulationInfo() {
    return modulationInfoCase_ == 5;
  }
  /**
   * <pre>
   * LR-FHSS modulation information.
   * </pre>
   *
   * <code>.gw.LrFhssModulationInfo lr_fhss_modulation_info = 5;</code>
   * @return The lrFhssModulationInfo.
   */
  @Override
  public LrFhssModulationInfo getLrFhssModulationInfo() {
    if (modulationInfoCase_ == 5) {
       return (LrFhssModulationInfo) modulationInfo_;
    }
    return LrFhssModulationInfo.getDefaultInstance();
  }
  /**
   * <pre>
   * LR-FHSS modulation information.
   * </pre>
   *
   * <code>.gw.LrFhssModulationInfo lr_fhss_modulation_info = 5;</code>
   */
  @Override
  public LrFhssModulationInfoOrBuilder getLrFhssModulationInfoOrBuilder() {
    if (modulationInfoCase_ == 5) {
       return (LrFhssModulationInfo) modulationInfo_;
    }
    return LrFhssModulationInfo.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (frequency_ != 0) {
      output.writeUInt32(1, frequency_);
    }
    if (modulation_ != io.chirpstack.api.Modulation.LORA.getNumber()) {
      output.writeEnum(2, modulation_);
    }
    if (modulationInfoCase_ == 3) {
      output.writeMessage(3, (LoraModulationInfo) modulationInfo_);
    }
    if (modulationInfoCase_ == 4) {
      output.writeMessage(4, (FskModulationInfo) modulationInfo_);
    }
    if (modulationInfoCase_ == 5) {
      output.writeMessage(5, (LrFhssModulationInfo) modulationInfo_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (frequency_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, frequency_);
    }
    if (modulation_ != io.chirpstack.api.Modulation.LORA.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, modulation_);
    }
    if (modulationInfoCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (LoraModulationInfo) modulationInfo_);
    }
    if (modulationInfoCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (FskModulationInfo) modulationInfo_);
    }
    if (modulationInfoCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (LrFhssModulationInfo) modulationInfo_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof UplinkTxInfoLegacy)) {
      return super.equals(obj);
    }
    UplinkTxInfoLegacy other = (UplinkTxInfoLegacy) obj;

    if (getFrequency()
        != other.getFrequency()) return false;
    if (modulation_ != other.modulation_) return false;
    if (!getModulationInfoCase().equals(other.getModulationInfoCase())) return false;
    switch (modulationInfoCase_) {
      case 3:
        if (!getLoraModulationInfo()
            .equals(other.getLoraModulationInfo())) return false;
        break;
      case 4:
        if (!getFskModulationInfo()
            .equals(other.getFskModulationInfo())) return false;
        break;
      case 5:
        if (!getLrFhssModulationInfo()
            .equals(other.getLrFhssModulationInfo())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FREQUENCY_FIELD_NUMBER;
    hash = (53 * hash) + getFrequency();
    hash = (37 * hash) + MODULATION_FIELD_NUMBER;
    hash = (53 * hash) + modulation_;
    switch (modulationInfoCase_) {
      case 3:
        hash = (37 * hash) + LORA_MODULATION_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getLoraModulationInfo().hashCode();
        break;
      case 4:
        hash = (37 * hash) + FSK_MODULATION_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getFskModulationInfo().hashCode();
        break;
      case 5:
        hash = (37 * hash) + LR_FHSS_MODULATION_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getLrFhssModulationInfo().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static UplinkTxInfoLegacy parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UplinkTxInfoLegacy parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UplinkTxInfoLegacy parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UplinkTxInfoLegacy parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UplinkTxInfoLegacy parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UplinkTxInfoLegacy parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UplinkTxInfoLegacy parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UplinkTxInfoLegacy parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static UplinkTxInfoLegacy parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static UplinkTxInfoLegacy parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static UplinkTxInfoLegacy parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UplinkTxInfoLegacy parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(UplinkTxInfoLegacy prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gw.UplinkTxInfoLegacy}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gw.UplinkTxInfoLegacy)
      UplinkTxInfoLegacyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GatewayProto.internal_static_gw_UplinkTxInfoLegacy_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GatewayProto.internal_static_gw_UplinkTxInfoLegacy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UplinkTxInfoLegacy.class, Builder.class);
    }

    // Construct using io.chirpstack.api.gw.UplinkTxInfoLegacy.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      frequency_ = 0;

      modulation_ = 0;

      if (loraModulationInfoBuilder_ != null) {
        loraModulationInfoBuilder_.clear();
      }
      if (fskModulationInfoBuilder_ != null) {
        fskModulationInfoBuilder_.clear();
      }
      if (lrFhssModulationInfoBuilder_ != null) {
        lrFhssModulationInfoBuilder_.clear();
      }
      modulationInfoCase_ = 0;
      modulationInfo_ = null;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GatewayProto.internal_static_gw_UplinkTxInfoLegacy_descriptor;
    }

    @Override
    public UplinkTxInfoLegacy getDefaultInstanceForType() {
      return UplinkTxInfoLegacy.getDefaultInstance();
    }

    @Override
    public UplinkTxInfoLegacy build() {
      UplinkTxInfoLegacy result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public UplinkTxInfoLegacy buildPartial() {
      UplinkTxInfoLegacy result = new UplinkTxInfoLegacy(this);
      result.frequency_ = frequency_;
      result.modulation_ = modulation_;
      if (modulationInfoCase_ == 3) {
        if (loraModulationInfoBuilder_ == null) {
          result.modulationInfo_ = modulationInfo_;
        } else {
          result.modulationInfo_ = loraModulationInfoBuilder_.build();
        }
      }
      if (modulationInfoCase_ == 4) {
        if (fskModulationInfoBuilder_ == null) {
          result.modulationInfo_ = modulationInfo_;
        } else {
          result.modulationInfo_ = fskModulationInfoBuilder_.build();
        }
      }
      if (modulationInfoCase_ == 5) {
        if (lrFhssModulationInfoBuilder_ == null) {
          result.modulationInfo_ = modulationInfo_;
        } else {
          result.modulationInfo_ = lrFhssModulationInfoBuilder_.build();
        }
      }
      result.modulationInfoCase_ = modulationInfoCase_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof UplinkTxInfoLegacy) {
        return mergeFrom((UplinkTxInfoLegacy)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(UplinkTxInfoLegacy other) {
      if (other == UplinkTxInfoLegacy.getDefaultInstance()) return this;
      if (other.getFrequency() != 0) {
        setFrequency(other.getFrequency());
      }
      if (other.modulation_ != 0) {
        setModulationValue(other.getModulationValue());
      }
      switch (other.getModulationInfoCase()) {
        case LORA_MODULATION_INFO: {
          mergeLoraModulationInfo(other.getLoraModulationInfo());
          break;
        }
        case FSK_MODULATION_INFO: {
          mergeFskModulationInfo(other.getFskModulationInfo());
          break;
        }
        case LR_FHSS_MODULATION_INFO: {
          mergeLrFhssModulationInfo(other.getLrFhssModulationInfo());
          break;
        }
        case MODULATIONINFO_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              frequency_ = input.readUInt32();

              break;
            } // case 8
            case 16: {
              modulation_ = input.readEnum();

              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getLoraModulationInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              modulationInfoCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getFskModulationInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              modulationInfoCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getLrFhssModulationInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              modulationInfoCase_ = 5;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int modulationInfoCase_ = 0;
    private Object modulationInfo_;
    public ModulationInfoCase
        getModulationInfoCase() {
      return ModulationInfoCase.forNumber(
          modulationInfoCase_);
    }

    public Builder clearModulationInfo() {
      modulationInfoCase_ = 0;
      modulationInfo_ = null;
      onChanged();
      return this;
    }


    private int frequency_ ;
    /**
     * <pre>
     * Frequency (Hz).
     * </pre>
     *
     * <code>uint32 frequency = 1;</code>
     * @return The frequency.
     */
    @Override
    public int getFrequency() {
      return frequency_;
    }
    /**
     * <pre>
     * Frequency (Hz).
     * </pre>
     *
     * <code>uint32 frequency = 1;</code>
     * @param value The frequency to set.
     * @return This builder for chaining.
     */
    public Builder setFrequency(int value) {
      
      frequency_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Frequency (Hz).
     * </pre>
     *
     * <code>uint32 frequency = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrequency() {
      
      frequency_ = 0;
      onChanged();
      return this;
    }

    private int modulation_ = 0;
    /**
     * <pre>
     * Modulation.
     * </pre>
     *
     * <code>.common.Modulation modulation = 2;</code>
     * @return The enum numeric value on the wire for modulation.
     */
    @Override public int getModulationValue() {
      return modulation_;
    }
    /**
     * <pre>
     * Modulation.
     * </pre>
     *
     * <code>.common.Modulation modulation = 2;</code>
     * @param value The enum numeric value on the wire for modulation to set.
     * @return This builder for chaining.
     */
    public Builder setModulationValue(int value) {
      
      modulation_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Modulation.
     * </pre>
     *
     * <code>.common.Modulation modulation = 2;</code>
     * @return The modulation.
     */
    @Override
    public io.chirpstack.api.Modulation getModulation() {
      @SuppressWarnings("deprecation")
      io.chirpstack.api.Modulation result = io.chirpstack.api.Modulation.valueOf(modulation_);
      return result == null ? io.chirpstack.api.Modulation.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Modulation.
     * </pre>
     *
     * <code>.common.Modulation modulation = 2;</code>
     * @param value The modulation to set.
     * @return This builder for chaining.
     */
    public Builder setModulation(io.chirpstack.api.Modulation value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      modulation_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Modulation.
     * </pre>
     *
     * <code>.common.Modulation modulation = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearModulation() {
      
      modulation_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        LoraModulationInfo, LoraModulationInfo.Builder, LoraModulationInfoOrBuilder> loraModulationInfoBuilder_;
    /**
     * <pre>
     * LoRa modulation information.
     * </pre>
     *
     * <code>.gw.LoraModulationInfo lora_modulation_info = 3;</code>
     * @return Whether the loraModulationInfo field is set.
     */
    @Override
    public boolean hasLoraModulationInfo() {
      return modulationInfoCase_ == 3;
    }
    /**
     * <pre>
     * LoRa modulation information.
     * </pre>
     *
     * <code>.gw.LoraModulationInfo lora_modulation_info = 3;</code>
     * @return The loraModulationInfo.
     */
    @Override
    public LoraModulationInfo getLoraModulationInfo() {
      if (loraModulationInfoBuilder_ == null) {
        if (modulationInfoCase_ == 3) {
          return (LoraModulationInfo) modulationInfo_;
        }
        return LoraModulationInfo.getDefaultInstance();
      } else {
        if (modulationInfoCase_ == 3) {
          return loraModulationInfoBuilder_.getMessage();
        }
        return LoraModulationInfo.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * LoRa modulation information.
     * </pre>
     *
     * <code>.gw.LoraModulationInfo lora_modulation_info = 3;</code>
     */
    public Builder setLoraModulationInfo(LoraModulationInfo value) {
      if (loraModulationInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        modulationInfo_ = value;
        onChanged();
      } else {
        loraModulationInfoBuilder_.setMessage(value);
      }
      modulationInfoCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * LoRa modulation information.
     * </pre>
     *
     * <code>.gw.LoraModulationInfo lora_modulation_info = 3;</code>
     */
    public Builder setLoraModulationInfo(
        LoraModulationInfo.Builder builderForValue) {
      if (loraModulationInfoBuilder_ == null) {
        modulationInfo_ = builderForValue.build();
        onChanged();
      } else {
        loraModulationInfoBuilder_.setMessage(builderForValue.build());
      }
      modulationInfoCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * LoRa modulation information.
     * </pre>
     *
     * <code>.gw.LoraModulationInfo lora_modulation_info = 3;</code>
     */
    public Builder mergeLoraModulationInfo(LoraModulationInfo value) {
      if (loraModulationInfoBuilder_ == null) {
        if (modulationInfoCase_ == 3 &&
            modulationInfo_ != LoraModulationInfo.getDefaultInstance()) {
          modulationInfo_ = LoraModulationInfo.newBuilder((LoraModulationInfo) modulationInfo_)
              .mergeFrom(value).buildPartial();
        } else {
          modulationInfo_ = value;
        }
        onChanged();
      } else {
        if (modulationInfoCase_ == 3) {
          loraModulationInfoBuilder_.mergeFrom(value);
        } else {
          loraModulationInfoBuilder_.setMessage(value);
        }
      }
      modulationInfoCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * LoRa modulation information.
     * </pre>
     *
     * <code>.gw.LoraModulationInfo lora_modulation_info = 3;</code>
     */
    public Builder clearLoraModulationInfo() {
      if (loraModulationInfoBuilder_ == null) {
        if (modulationInfoCase_ == 3) {
          modulationInfoCase_ = 0;
          modulationInfo_ = null;
          onChanged();
        }
      } else {
        if (modulationInfoCase_ == 3) {
          modulationInfoCase_ = 0;
          modulationInfo_ = null;
        }
        loraModulationInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * LoRa modulation information.
     * </pre>
     *
     * <code>.gw.LoraModulationInfo lora_modulation_info = 3;</code>
     */
    public LoraModulationInfo.Builder getLoraModulationInfoBuilder() {
      return getLoraModulationInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * LoRa modulation information.
     * </pre>
     *
     * <code>.gw.LoraModulationInfo lora_modulation_info = 3;</code>
     */
    @Override
    public LoraModulationInfoOrBuilder getLoraModulationInfoOrBuilder() {
      if ((modulationInfoCase_ == 3) && (loraModulationInfoBuilder_ != null)) {
        return loraModulationInfoBuilder_.getMessageOrBuilder();
      } else {
        if (modulationInfoCase_ == 3) {
          return (LoraModulationInfo) modulationInfo_;
        }
        return LoraModulationInfo.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * LoRa modulation information.
     * </pre>
     *
     * <code>.gw.LoraModulationInfo lora_modulation_info = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        LoraModulationInfo, LoraModulationInfo.Builder, LoraModulationInfoOrBuilder>
        getLoraModulationInfoFieldBuilder() {
      if (loraModulationInfoBuilder_ == null) {
        if (!(modulationInfoCase_ == 3)) {
          modulationInfo_ = LoraModulationInfo.getDefaultInstance();
        }
        loraModulationInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            LoraModulationInfo, LoraModulationInfo.Builder, LoraModulationInfoOrBuilder>(
                (LoraModulationInfo) modulationInfo_,
                getParentForChildren(),
                isClean());
        modulationInfo_ = null;
      }
      modulationInfoCase_ = 3;
      onChanged();;
      return loraModulationInfoBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        FskModulationInfo, FskModulationInfo.Builder, FskModulationInfoOrBuilder> fskModulationInfoBuilder_;
    /**
     * <pre>
     * FSK modulation information.
     * </pre>
     *
     * <code>.gw.FskModulationInfo fsk_modulation_info = 4;</code>
     * @return Whether the fskModulationInfo field is set.
     */
    @Override
    public boolean hasFskModulationInfo() {
      return modulationInfoCase_ == 4;
    }
    /**
     * <pre>
     * FSK modulation information.
     * </pre>
     *
     * <code>.gw.FskModulationInfo fsk_modulation_info = 4;</code>
     * @return The fskModulationInfo.
     */
    @Override
    public FskModulationInfo getFskModulationInfo() {
      if (fskModulationInfoBuilder_ == null) {
        if (modulationInfoCase_ == 4) {
          return (FskModulationInfo) modulationInfo_;
        }
        return FskModulationInfo.getDefaultInstance();
      } else {
        if (modulationInfoCase_ == 4) {
          return fskModulationInfoBuilder_.getMessage();
        }
        return FskModulationInfo.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * FSK modulation information.
     * </pre>
     *
     * <code>.gw.FskModulationInfo fsk_modulation_info = 4;</code>
     */
    public Builder setFskModulationInfo(FskModulationInfo value) {
      if (fskModulationInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        modulationInfo_ = value;
        onChanged();
      } else {
        fskModulationInfoBuilder_.setMessage(value);
      }
      modulationInfoCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * FSK modulation information.
     * </pre>
     *
     * <code>.gw.FskModulationInfo fsk_modulation_info = 4;</code>
     */
    public Builder setFskModulationInfo(
        FskModulationInfo.Builder builderForValue) {
      if (fskModulationInfoBuilder_ == null) {
        modulationInfo_ = builderForValue.build();
        onChanged();
      } else {
        fskModulationInfoBuilder_.setMessage(builderForValue.build());
      }
      modulationInfoCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * FSK modulation information.
     * </pre>
     *
     * <code>.gw.FskModulationInfo fsk_modulation_info = 4;</code>
     */
    public Builder mergeFskModulationInfo(FskModulationInfo value) {
      if (fskModulationInfoBuilder_ == null) {
        if (modulationInfoCase_ == 4 &&
            modulationInfo_ != FskModulationInfo.getDefaultInstance()) {
          modulationInfo_ = FskModulationInfo.newBuilder((FskModulationInfo) modulationInfo_)
              .mergeFrom(value).buildPartial();
        } else {
          modulationInfo_ = value;
        }
        onChanged();
      } else {
        if (modulationInfoCase_ == 4) {
          fskModulationInfoBuilder_.mergeFrom(value);
        } else {
          fskModulationInfoBuilder_.setMessage(value);
        }
      }
      modulationInfoCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * FSK modulation information.
     * </pre>
     *
     * <code>.gw.FskModulationInfo fsk_modulation_info = 4;</code>
     */
    public Builder clearFskModulationInfo() {
      if (fskModulationInfoBuilder_ == null) {
        if (modulationInfoCase_ == 4) {
          modulationInfoCase_ = 0;
          modulationInfo_ = null;
          onChanged();
        }
      } else {
        if (modulationInfoCase_ == 4) {
          modulationInfoCase_ = 0;
          modulationInfo_ = null;
        }
        fskModulationInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * FSK modulation information.
     * </pre>
     *
     * <code>.gw.FskModulationInfo fsk_modulation_info = 4;</code>
     */
    public FskModulationInfo.Builder getFskModulationInfoBuilder() {
      return getFskModulationInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * FSK modulation information.
     * </pre>
     *
     * <code>.gw.FskModulationInfo fsk_modulation_info = 4;</code>
     */
    @Override
    public FskModulationInfoOrBuilder getFskModulationInfoOrBuilder() {
      if ((modulationInfoCase_ == 4) && (fskModulationInfoBuilder_ != null)) {
        return fskModulationInfoBuilder_.getMessageOrBuilder();
      } else {
        if (modulationInfoCase_ == 4) {
          return (FskModulationInfo) modulationInfo_;
        }
        return FskModulationInfo.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * FSK modulation information.
     * </pre>
     *
     * <code>.gw.FskModulationInfo fsk_modulation_info = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        FskModulationInfo, FskModulationInfo.Builder, FskModulationInfoOrBuilder>
        getFskModulationInfoFieldBuilder() {
      if (fskModulationInfoBuilder_ == null) {
        if (!(modulationInfoCase_ == 4)) {
          modulationInfo_ = FskModulationInfo.getDefaultInstance();
        }
        fskModulationInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            FskModulationInfo, FskModulationInfo.Builder, FskModulationInfoOrBuilder>(
                (FskModulationInfo) modulationInfo_,
                getParentForChildren(),
                isClean());
        modulationInfo_ = null;
      }
      modulationInfoCase_ = 4;
      onChanged();;
      return fskModulationInfoBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        LrFhssModulationInfo, LrFhssModulationInfo.Builder, LrFhssModulationInfoOrBuilder> lrFhssModulationInfoBuilder_;
    /**
     * <pre>
     * LR-FHSS modulation information.
     * </pre>
     *
     * <code>.gw.LrFhssModulationInfo lr_fhss_modulation_info = 5;</code>
     * @return Whether the lrFhssModulationInfo field is set.
     */
    @Override
    public boolean hasLrFhssModulationInfo() {
      return modulationInfoCase_ == 5;
    }
    /**
     * <pre>
     * LR-FHSS modulation information.
     * </pre>
     *
     * <code>.gw.LrFhssModulationInfo lr_fhss_modulation_info = 5;</code>
     * @return The lrFhssModulationInfo.
     */
    @Override
    public LrFhssModulationInfo getLrFhssModulationInfo() {
      if (lrFhssModulationInfoBuilder_ == null) {
        if (modulationInfoCase_ == 5) {
          return (LrFhssModulationInfo) modulationInfo_;
        }
        return LrFhssModulationInfo.getDefaultInstance();
      } else {
        if (modulationInfoCase_ == 5) {
          return lrFhssModulationInfoBuilder_.getMessage();
        }
        return LrFhssModulationInfo.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * LR-FHSS modulation information.
     * </pre>
     *
     * <code>.gw.LrFhssModulationInfo lr_fhss_modulation_info = 5;</code>
     */
    public Builder setLrFhssModulationInfo(LrFhssModulationInfo value) {
      if (lrFhssModulationInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        modulationInfo_ = value;
        onChanged();
      } else {
        lrFhssModulationInfoBuilder_.setMessage(value);
      }
      modulationInfoCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * LR-FHSS modulation information.
     * </pre>
     *
     * <code>.gw.LrFhssModulationInfo lr_fhss_modulation_info = 5;</code>
     */
    public Builder setLrFhssModulationInfo(
        LrFhssModulationInfo.Builder builderForValue) {
      if (lrFhssModulationInfoBuilder_ == null) {
        modulationInfo_ = builderForValue.build();
        onChanged();
      } else {
        lrFhssModulationInfoBuilder_.setMessage(builderForValue.build());
      }
      modulationInfoCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * LR-FHSS modulation information.
     * </pre>
     *
     * <code>.gw.LrFhssModulationInfo lr_fhss_modulation_info = 5;</code>
     */
    public Builder mergeLrFhssModulationInfo(LrFhssModulationInfo value) {
      if (lrFhssModulationInfoBuilder_ == null) {
        if (modulationInfoCase_ == 5 &&
            modulationInfo_ != LrFhssModulationInfo.getDefaultInstance()) {
          modulationInfo_ = LrFhssModulationInfo.newBuilder((LrFhssModulationInfo) modulationInfo_)
              .mergeFrom(value).buildPartial();
        } else {
          modulationInfo_ = value;
        }
        onChanged();
      } else {
        if (modulationInfoCase_ == 5) {
          lrFhssModulationInfoBuilder_.mergeFrom(value);
        } else {
          lrFhssModulationInfoBuilder_.setMessage(value);
        }
      }
      modulationInfoCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * LR-FHSS modulation information.
     * </pre>
     *
     * <code>.gw.LrFhssModulationInfo lr_fhss_modulation_info = 5;</code>
     */
    public Builder clearLrFhssModulationInfo() {
      if (lrFhssModulationInfoBuilder_ == null) {
        if (modulationInfoCase_ == 5) {
          modulationInfoCase_ = 0;
          modulationInfo_ = null;
          onChanged();
        }
      } else {
        if (modulationInfoCase_ == 5) {
          modulationInfoCase_ = 0;
          modulationInfo_ = null;
        }
        lrFhssModulationInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * LR-FHSS modulation information.
     * </pre>
     *
     * <code>.gw.LrFhssModulationInfo lr_fhss_modulation_info = 5;</code>
     */
    public LrFhssModulationInfo.Builder getLrFhssModulationInfoBuilder() {
      return getLrFhssModulationInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * LR-FHSS modulation information.
     * </pre>
     *
     * <code>.gw.LrFhssModulationInfo lr_fhss_modulation_info = 5;</code>
     */
    @Override
    public LrFhssModulationInfoOrBuilder getLrFhssModulationInfoOrBuilder() {
      if ((modulationInfoCase_ == 5) && (lrFhssModulationInfoBuilder_ != null)) {
        return lrFhssModulationInfoBuilder_.getMessageOrBuilder();
      } else {
        if (modulationInfoCase_ == 5) {
          return (LrFhssModulationInfo) modulationInfo_;
        }
        return LrFhssModulationInfo.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * LR-FHSS modulation information.
     * </pre>
     *
     * <code>.gw.LrFhssModulationInfo lr_fhss_modulation_info = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        LrFhssModulationInfo, LrFhssModulationInfo.Builder, LrFhssModulationInfoOrBuilder>
        getLrFhssModulationInfoFieldBuilder() {
      if (lrFhssModulationInfoBuilder_ == null) {
        if (!(modulationInfoCase_ == 5)) {
          modulationInfo_ = LrFhssModulationInfo.getDefaultInstance();
        }
        lrFhssModulationInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            LrFhssModulationInfo, LrFhssModulationInfo.Builder, LrFhssModulationInfoOrBuilder>(
                (LrFhssModulationInfo) modulationInfo_,
                getParentForChildren(),
                isClean());
        modulationInfo_ = null;
      }
      modulationInfoCase_ = 5;
      onChanged();;
      return lrFhssModulationInfoBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gw.UplinkTxInfoLegacy)
  }

  // @@protoc_insertion_point(class_scope:gw.UplinkTxInfoLegacy)
  private static final UplinkTxInfoLegacy DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new UplinkTxInfoLegacy();
  }

  public static UplinkTxInfoLegacy getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UplinkTxInfoLegacy>
      PARSER = new com.google.protobuf.AbstractParser<UplinkTxInfoLegacy>() {
    @Override
    public UplinkTxInfoLegacy parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UplinkTxInfoLegacy> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<UplinkTxInfoLegacy> getParserForType() {
    return PARSER;
  }

  @Override
  public UplinkTxInfoLegacy getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

