// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/iot_config.proto

package com.helium.grpc;

public interface gateway_infoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.iot_config.gateway_info)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The public key binary address and on-chain identity of the gateway
   * </pre>
   *
   * <code>bytes address = 1;</code>
   * @return The address.
   */
  com.google.protobuf.ByteString getAddress();

  /**
   * <pre>
   * Whether or not the hotspot participates in PoC or only transfers data
   * </pre>
   *
   * <code>bool is_full_hotspot = 2;</code>
   * @return The isFullHotspot.
   */
  boolean getIsFullHotspot();

  /**
   * <pre>
   * The gateway's metadata as recorded on the blockchain
   * </pre>
   *
   * <code>.helium.iot_config.gateway_metadata metadata = 3;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * The gateway's metadata as recorded on the blockchain
   * </pre>
   *
   * <code>.helium.iot_config.gateway_metadata metadata = 3;</code>
   * @return The metadata.
   */
  gateway_metadata getMetadata();
  /**
   * <pre>
   * The gateway's metadata as recorded on the blockchain
   * </pre>
   *
   * <code>.helium.iot_config.gateway_metadata metadata = 3;</code>
   */
  gateway_metadataOrBuilder getMetadataOrBuilder();
}
