// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service/iot_config.proto
// Protobuf Java Version: 4.29.2

package com.helium.grpc;

/**
 * <pre>
 * Route definition
 * </pre>
 *
 * Protobuf type {@code helium.iot_config.route_v1}
 */
public final class route_v1 extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:helium.iot_config.route_v1)
    route_v1OrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      route_v1.class.getName());
  }
  // Use route_v1.newBuilder() to construct.
  private route_v1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private route_v1() {
    id_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.helium.grpc.IotConfig.internal_static_helium_iot_config_route_v1_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.helium.grpc.IotConfig.internal_static_helium_iot_config_route_v1_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.helium.grpc.route_v1.class, com.helium.grpc.route_v1.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <pre>
   * UUID
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * UUID
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NET_ID_FIELD_NUMBER = 2;
  private int netId_ = 0;
  /**
   * <pre>
   * LoraWan Network ID
   * </pre>
   *
   * <code>uint32 net_id = 2;</code>
   * @return The netId.
   */
  @java.lang.Override
  public int getNetId() {
    return netId_;
  }

  public static final int OUI_FIELD_NUMBER = 3;
  private long oui_ = 0L;
  /**
   * <pre>
   * Organization Unique ID
   * </pre>
   *
   * <code>uint64 oui = 3;</code>
   * @return The oui.
   */
  @java.lang.Override
  public long getOui() {
    return oui_;
  }

  public static final int SERVER_FIELD_NUMBER = 4;
  private com.helium.grpc.server_v1 server_;
  /**
   * <code>.helium.iot_config.server_v1 server = 4;</code>
   * @return Whether the server field is set.
   */
  @java.lang.Override
  public boolean hasServer() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.helium.iot_config.server_v1 server = 4;</code>
   * @return The server.
   */
  @java.lang.Override
  public com.helium.grpc.server_v1 getServer() {
    return server_ == null ? com.helium.grpc.server_v1.getDefaultInstance() : server_;
  }
  /**
   * <code>.helium.iot_config.server_v1 server = 4;</code>
   */
  @java.lang.Override
  public com.helium.grpc.server_v1OrBuilder getServerOrBuilder() {
    return server_ == null ? com.helium.grpc.server_v1.getDefaultInstance() : server_;
  }

  public static final int MAX_COPIES_FIELD_NUMBER = 5;
  private int maxCopies_ = 0;
  /**
   * <pre>
   * Number of packet copies bought by this route
   * </pre>
   *
   * <code>uint32 max_copies = 5;</code>
   * @return The maxCopies.
   */
  @java.lang.Override
  public int getMaxCopies() {
    return maxCopies_;
  }

  public static final int ACTIVE_FIELD_NUMBER = 6;
  private boolean active_ = false;
  /**
   * <code>bool active = 6;</code>
   * @return The active.
   */
  @java.lang.Override
  public boolean getActive() {
    return active_;
  }

  public static final int LOCKED_FIELD_NUMBER = 7;
  private boolean locked_ = false;
  /**
   * <pre>
   * Is route locked because of no payment
   * </pre>
   *
   * <code>bool locked = 7;</code>
   * @return The locked.
   */
  @java.lang.Override
  public boolean getLocked() {
    return locked_;
  }

  public static final int IGNORE_EMPTY_SKF_FIELD_NUMBER = 8;
  private boolean ignoreEmptySkf_ = false;
  /**
   * <pre>
   * If true, routes are blocked whose devaddrs have empty session key filters
   * </pre>
   *
   * <code>bool ignore_empty_skf = 8;</code>
   * @return The ignoreEmptySkf.
   */
  @java.lang.Override
  public boolean getIgnoreEmptySkf() {
    return ignoreEmptySkf_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
    }
    if (netId_ != 0) {
      output.writeUInt32(2, netId_);
    }
    if (oui_ != 0L) {
      output.writeUInt64(3, oui_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getServer());
    }
    if (maxCopies_ != 0) {
      output.writeUInt32(5, maxCopies_);
    }
    if (active_ != false) {
      output.writeBool(6, active_);
    }
    if (locked_ != false) {
      output.writeBool(7, locked_);
    }
    if (ignoreEmptySkf_ != false) {
      output.writeBool(8, ignoreEmptySkf_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
    }
    if (netId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, netId_);
    }
    if (oui_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, oui_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getServer());
    }
    if (maxCopies_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, maxCopies_);
    }
    if (active_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, active_);
    }
    if (locked_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, locked_);
    }
    if (ignoreEmptySkf_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, ignoreEmptySkf_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.helium.grpc.route_v1)) {
      return super.equals(obj);
    }
    com.helium.grpc.route_v1 other = (com.helium.grpc.route_v1) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (getNetId()
        != other.getNetId()) return false;
    if (getOui()
        != other.getOui()) return false;
    if (hasServer() != other.hasServer()) return false;
    if (hasServer()) {
      if (!getServer()
          .equals(other.getServer())) return false;
    }
    if (getMaxCopies()
        != other.getMaxCopies()) return false;
    if (getActive()
        != other.getActive()) return false;
    if (getLocked()
        != other.getLocked()) return false;
    if (getIgnoreEmptySkf()
        != other.getIgnoreEmptySkf()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NET_ID_FIELD_NUMBER;
    hash = (53 * hash) + getNetId();
    hash = (37 * hash) + OUI_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOui());
    if (hasServer()) {
      hash = (37 * hash) + SERVER_FIELD_NUMBER;
      hash = (53 * hash) + getServer().hashCode();
    }
    hash = (37 * hash) + MAX_COPIES_FIELD_NUMBER;
    hash = (53 * hash) + getMaxCopies();
    hash = (37 * hash) + ACTIVE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getActive());
    hash = (37 * hash) + LOCKED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getLocked());
    hash = (37 * hash) + IGNORE_EMPTY_SKF_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIgnoreEmptySkf());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.helium.grpc.route_v1 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.helium.grpc.route_v1 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.helium.grpc.route_v1 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.helium.grpc.route_v1 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.helium.grpc.route_v1 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.helium.grpc.route_v1 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.helium.grpc.route_v1 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.helium.grpc.route_v1 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.helium.grpc.route_v1 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.helium.grpc.route_v1 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.helium.grpc.route_v1 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.helium.grpc.route_v1 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.helium.grpc.route_v1 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Route definition
   * </pre>
   *
   * Protobuf type {@code helium.iot_config.route_v1}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helium.iot_config.route_v1)
      com.helium.grpc.route_v1OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.helium.grpc.IotConfig.internal_static_helium_iot_config_route_v1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.helium.grpc.IotConfig.internal_static_helium_iot_config_route_v1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.helium.grpc.route_v1.class, com.helium.grpc.route_v1.Builder.class);
    }

    // Construct using com.helium.grpc.route_v1.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getServerFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      netId_ = 0;
      oui_ = 0L;
      server_ = null;
      if (serverBuilder_ != null) {
        serverBuilder_.dispose();
        serverBuilder_ = null;
      }
      maxCopies_ = 0;
      active_ = false;
      locked_ = false;
      ignoreEmptySkf_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.helium.grpc.IotConfig.internal_static_helium_iot_config_route_v1_descriptor;
    }

    @java.lang.Override
    public com.helium.grpc.route_v1 getDefaultInstanceForType() {
      return com.helium.grpc.route_v1.getDefaultInstance();
    }

    @java.lang.Override
    public com.helium.grpc.route_v1 build() {
      com.helium.grpc.route_v1 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.helium.grpc.route_v1 buildPartial() {
      com.helium.grpc.route_v1 result = new com.helium.grpc.route_v1(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.helium.grpc.route_v1 result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.netId_ = netId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.oui_ = oui_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.server_ = serverBuilder_ == null
            ? server_
            : serverBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.maxCopies_ = maxCopies_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.active_ = active_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.locked_ = locked_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.ignoreEmptySkf_ = ignoreEmptySkf_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.helium.grpc.route_v1) {
        return mergeFrom((com.helium.grpc.route_v1)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.helium.grpc.route_v1 other) {
      if (other == com.helium.grpc.route_v1.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getNetId() != 0) {
        setNetId(other.getNetId());
      }
      if (other.getOui() != 0L) {
        setOui(other.getOui());
      }
      if (other.hasServer()) {
        mergeServer(other.getServer());
      }
      if (other.getMaxCopies() != 0) {
        setMaxCopies(other.getMaxCopies());
      }
      if (other.getActive() != false) {
        setActive(other.getActive());
      }
      if (other.getLocked() != false) {
        setLocked(other.getLocked());
      }
      if (other.getIgnoreEmptySkf() != false) {
        setIgnoreEmptySkf(other.getIgnoreEmptySkf());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              netId_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              oui_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  getServerFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              maxCopies_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              active_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              locked_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              ignoreEmptySkf_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int netId_ ;
    /**
     * <pre>
     * LoraWan Network ID
     * </pre>
     *
     * <code>uint32 net_id = 2;</code>
     * @return The netId.
     */
    @java.lang.Override
    public int getNetId() {
      return netId_;
    }
    /**
     * <pre>
     * LoraWan Network ID
     * </pre>
     *
     * <code>uint32 net_id = 2;</code>
     * @param value The netId to set.
     * @return This builder for chaining.
     */
    public Builder setNetId(int value) {

      netId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * LoraWan Network ID
     * </pre>
     *
     * <code>uint32 net_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      netId_ = 0;
      onChanged();
      return this;
    }

    private long oui_ ;
    /**
     * <pre>
     * Organization Unique ID
     * </pre>
     *
     * <code>uint64 oui = 3;</code>
     * @return The oui.
     */
    @java.lang.Override
    public long getOui() {
      return oui_;
    }
    /**
     * <pre>
     * Organization Unique ID
     * </pre>
     *
     * <code>uint64 oui = 3;</code>
     * @param value The oui to set.
     * @return This builder for chaining.
     */
    public Builder setOui(long value) {

      oui_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Organization Unique ID
     * </pre>
     *
     * <code>uint64 oui = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOui() {
      bitField0_ = (bitField0_ & ~0x00000004);
      oui_ = 0L;
      onChanged();
      return this;
    }

    private com.helium.grpc.server_v1 server_;
    private com.google.protobuf.SingleFieldBuilder<
        com.helium.grpc.server_v1, com.helium.grpc.server_v1.Builder, com.helium.grpc.server_v1OrBuilder> serverBuilder_;
    /**
     * <code>.helium.iot_config.server_v1 server = 4;</code>
     * @return Whether the server field is set.
     */
    public boolean hasServer() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.helium.iot_config.server_v1 server = 4;</code>
     * @return The server.
     */
    public com.helium.grpc.server_v1 getServer() {
      if (serverBuilder_ == null) {
        return server_ == null ? com.helium.grpc.server_v1.getDefaultInstance() : server_;
      } else {
        return serverBuilder_.getMessage();
      }
    }
    /**
     * <code>.helium.iot_config.server_v1 server = 4;</code>
     */
    public Builder setServer(com.helium.grpc.server_v1 value) {
      if (serverBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        server_ = value;
      } else {
        serverBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.helium.iot_config.server_v1 server = 4;</code>
     */
    public Builder setServer(
        com.helium.grpc.server_v1.Builder builderForValue) {
      if (serverBuilder_ == null) {
        server_ = builderForValue.build();
      } else {
        serverBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.helium.iot_config.server_v1 server = 4;</code>
     */
    public Builder mergeServer(com.helium.grpc.server_v1 value) {
      if (serverBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          server_ != null &&
          server_ != com.helium.grpc.server_v1.getDefaultInstance()) {
          getServerBuilder().mergeFrom(value);
        } else {
          server_ = value;
        }
      } else {
        serverBuilder_.mergeFrom(value);
      }
      if (server_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.helium.iot_config.server_v1 server = 4;</code>
     */
    public Builder clearServer() {
      bitField0_ = (bitField0_ & ~0x00000008);
      server_ = null;
      if (serverBuilder_ != null) {
        serverBuilder_.dispose();
        serverBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.helium.iot_config.server_v1 server = 4;</code>
     */
    public com.helium.grpc.server_v1.Builder getServerBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getServerFieldBuilder().getBuilder();
    }
    /**
     * <code>.helium.iot_config.server_v1 server = 4;</code>
     */
    public com.helium.grpc.server_v1OrBuilder getServerOrBuilder() {
      if (serverBuilder_ != null) {
        return serverBuilder_.getMessageOrBuilder();
      } else {
        return server_ == null ?
            com.helium.grpc.server_v1.getDefaultInstance() : server_;
      }
    }
    /**
     * <code>.helium.iot_config.server_v1 server = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.helium.grpc.server_v1, com.helium.grpc.server_v1.Builder, com.helium.grpc.server_v1OrBuilder> 
        getServerFieldBuilder() {
      if (serverBuilder_ == null) {
        serverBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.helium.grpc.server_v1, com.helium.grpc.server_v1.Builder, com.helium.grpc.server_v1OrBuilder>(
                getServer(),
                getParentForChildren(),
                isClean());
        server_ = null;
      }
      return serverBuilder_;
    }

    private int maxCopies_ ;
    /**
     * <pre>
     * Number of packet copies bought by this route
     * </pre>
     *
     * <code>uint32 max_copies = 5;</code>
     * @return The maxCopies.
     */
    @java.lang.Override
    public int getMaxCopies() {
      return maxCopies_;
    }
    /**
     * <pre>
     * Number of packet copies bought by this route
     * </pre>
     *
     * <code>uint32 max_copies = 5;</code>
     * @param value The maxCopies to set.
     * @return This builder for chaining.
     */
    public Builder setMaxCopies(int value) {

      maxCopies_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Number of packet copies bought by this route
     * </pre>
     *
     * <code>uint32 max_copies = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxCopies() {
      bitField0_ = (bitField0_ & ~0x00000010);
      maxCopies_ = 0;
      onChanged();
      return this;
    }

    private boolean active_ ;
    /**
     * <code>bool active = 6;</code>
     * @return The active.
     */
    @java.lang.Override
    public boolean getActive() {
      return active_;
    }
    /**
     * <code>bool active = 6;</code>
     * @param value The active to set.
     * @return This builder for chaining.
     */
    public Builder setActive(boolean value) {

      active_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bool active = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearActive() {
      bitField0_ = (bitField0_ & ~0x00000020);
      active_ = false;
      onChanged();
      return this;
    }

    private boolean locked_ ;
    /**
     * <pre>
     * Is route locked because of no payment
     * </pre>
     *
     * <code>bool locked = 7;</code>
     * @return The locked.
     */
    @java.lang.Override
    public boolean getLocked() {
      return locked_;
    }
    /**
     * <pre>
     * Is route locked because of no payment
     * </pre>
     *
     * <code>bool locked = 7;</code>
     * @param value The locked to set.
     * @return This builder for chaining.
     */
    public Builder setLocked(boolean value) {

      locked_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Is route locked because of no payment
     * </pre>
     *
     * <code>bool locked = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocked() {
      bitField0_ = (bitField0_ & ~0x00000040);
      locked_ = false;
      onChanged();
      return this;
    }

    private boolean ignoreEmptySkf_ ;
    /**
     * <pre>
     * If true, routes are blocked whose devaddrs have empty session key filters
     * </pre>
     *
     * <code>bool ignore_empty_skf = 8;</code>
     * @return The ignoreEmptySkf.
     */
    @java.lang.Override
    public boolean getIgnoreEmptySkf() {
      return ignoreEmptySkf_;
    }
    /**
     * <pre>
     * If true, routes are blocked whose devaddrs have empty session key filters
     * </pre>
     *
     * <code>bool ignore_empty_skf = 8;</code>
     * @param value The ignoreEmptySkf to set.
     * @return This builder for chaining.
     */
    public Builder setIgnoreEmptySkf(boolean value) {

      ignoreEmptySkf_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If true, routes are blocked whose devaddrs have empty session key filters
     * </pre>
     *
     * <code>bool ignore_empty_skf = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearIgnoreEmptySkf() {
      bitField0_ = (bitField0_ & ~0x00000080);
      ignoreEmptySkf_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:helium.iot_config.route_v1)
  }

  // @@protoc_insertion_point(class_scope:helium.iot_config.route_v1)
  private static final com.helium.grpc.route_v1 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.helium.grpc.route_v1();
  }

  public static com.helium.grpc.route_v1 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<route_v1>
      PARSER = new com.google.protobuf.AbstractParser<route_v1>() {
    @java.lang.Override
    public route_v1 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<route_v1> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<route_v1> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.helium.grpc.route_v1 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

