// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/iot_config.proto

package com.helium.grpc;

/**
 * Protobuf type {@code helium.iot_config.skf_v1}
 */
public final class skf_v1 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:helium.iot_config.skf_v1)
    skf_v1OrBuilder {
private static final long serialVersionUID = 0L;
  // Use skf_v1.newBuilder() to construct.
  private skf_v1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private skf_v1() {
    routeId_ = "";
    sessionKey_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new skf_v1();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.helium.grpc.IotConfig.internal_static_helium_iot_config_skf_v1_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.helium.grpc.IotConfig.internal_static_helium_iot_config_skf_v1_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.helium.grpc.skf_v1.class, com.helium.grpc.skf_v1.Builder.class);
  }

  public static final int ROUTE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object routeId_ = "";
  /**
   * <code>string route_id = 1;</code>
   * @return The routeId.
   */
  @java.lang.Override
  public java.lang.String getRouteId() {
    java.lang.Object ref = routeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      routeId_ = s;
      return s;
    }
  }
  /**
   * <code>string route_id = 1;</code>
   * @return The bytes for routeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRouteIdBytes() {
    java.lang.Object ref = routeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      routeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVADDR_FIELD_NUMBER = 2;
  private int devaddr_ = 0;
  /**
   * <code>uint32 devaddr = 2;</code>
   * @return The devaddr.
   */
  @java.lang.Override
  public int getDevaddr() {
    return devaddr_;
  }

  public static final int SESSION_KEY_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionKey_ = "";
  /**
   * <pre>
   * the hex-encoded string of the binary session key
   * </pre>
   *
   * <code>string session_key = 3;</code>
   * @return The sessionKey.
   */
  @java.lang.Override
  public java.lang.String getSessionKey() {
    java.lang.Object ref = sessionKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionKey_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * the hex-encoded string of the binary session key
   * </pre>
   *
   * <code>string session_key = 3;</code>
   * @return The bytes for sessionKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionKeyBytes() {
    java.lang.Object ref = sessionKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(routeId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, routeId_);
    }
    if (devaddr_ != 0) {
      output.writeUInt32(2, devaddr_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sessionKey_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sessionKey_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(routeId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, routeId_);
    }
    if (devaddr_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, devaddr_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sessionKey_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sessionKey_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.helium.grpc.skf_v1)) {
      return super.equals(obj);
    }
    com.helium.grpc.skf_v1 other = (com.helium.grpc.skf_v1) obj;

    if (!getRouteId()
        .equals(other.getRouteId())) return false;
    if (getDevaddr()
        != other.getDevaddr()) return false;
    if (!getSessionKey()
        .equals(other.getSessionKey())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROUTE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRouteId().hashCode();
    hash = (37 * hash) + DEVADDR_FIELD_NUMBER;
    hash = (53 * hash) + getDevaddr();
    hash = (37 * hash) + SESSION_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getSessionKey().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.helium.grpc.skf_v1 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.helium.grpc.skf_v1 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.helium.grpc.skf_v1 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.helium.grpc.skf_v1 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.helium.grpc.skf_v1 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.helium.grpc.skf_v1 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.helium.grpc.skf_v1 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.helium.grpc.skf_v1 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.helium.grpc.skf_v1 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.helium.grpc.skf_v1 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.helium.grpc.skf_v1 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.helium.grpc.skf_v1 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.helium.grpc.skf_v1 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code helium.iot_config.skf_v1}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helium.iot_config.skf_v1)
      com.helium.grpc.skf_v1OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.helium.grpc.IotConfig.internal_static_helium_iot_config_skf_v1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.helium.grpc.IotConfig.internal_static_helium_iot_config_skf_v1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.helium.grpc.skf_v1.class, com.helium.grpc.skf_v1.Builder.class);
    }

    // Construct using com.helium.grpc.skf_v1.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      routeId_ = "";
      devaddr_ = 0;
      sessionKey_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.helium.grpc.IotConfig.internal_static_helium_iot_config_skf_v1_descriptor;
    }

    @java.lang.Override
    public com.helium.grpc.skf_v1 getDefaultInstanceForType() {
      return com.helium.grpc.skf_v1.getDefaultInstance();
    }

    @java.lang.Override
    public com.helium.grpc.skf_v1 build() {
      com.helium.grpc.skf_v1 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.helium.grpc.skf_v1 buildPartial() {
      com.helium.grpc.skf_v1 result = new com.helium.grpc.skf_v1(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.helium.grpc.skf_v1 result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.routeId_ = routeId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.devaddr_ = devaddr_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.sessionKey_ = sessionKey_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.helium.grpc.skf_v1) {
        return mergeFrom((com.helium.grpc.skf_v1)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.helium.grpc.skf_v1 other) {
      if (other == com.helium.grpc.skf_v1.getDefaultInstance()) return this;
      if (!other.getRouteId().isEmpty()) {
        routeId_ = other.routeId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getDevaddr() != 0) {
        setDevaddr(other.getDevaddr());
      }
      if (!other.getSessionKey().isEmpty()) {
        sessionKey_ = other.sessionKey_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              routeId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              devaddr_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              sessionKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object routeId_ = "";
    /**
     * <code>string route_id = 1;</code>
     * @return The routeId.
     */
    public java.lang.String getRouteId() {
      java.lang.Object ref = routeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        routeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string route_id = 1;</code>
     * @return The bytes for routeId.
     */
    public com.google.protobuf.ByteString
        getRouteIdBytes() {
      java.lang.Object ref = routeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        routeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string route_id = 1;</code>
     * @param value The routeId to set.
     * @return This builder for chaining.
     */
    public Builder setRouteId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      routeId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string route_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRouteId() {
      routeId_ = getDefaultInstance().getRouteId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string route_id = 1;</code>
     * @param value The bytes for routeId to set.
     * @return This builder for chaining.
     */
    public Builder setRouteIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      routeId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int devaddr_ ;
    /**
     * <code>uint32 devaddr = 2;</code>
     * @return The devaddr.
     */
    @java.lang.Override
    public int getDevaddr() {
      return devaddr_;
    }
    /**
     * <code>uint32 devaddr = 2;</code>
     * @param value The devaddr to set.
     * @return This builder for chaining.
     */
    public Builder setDevaddr(int value) {

      devaddr_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 devaddr = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDevaddr() {
      bitField0_ = (bitField0_ & ~0x00000002);
      devaddr_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object sessionKey_ = "";
    /**
     * <pre>
     * the hex-encoded string of the binary session key
     * </pre>
     *
     * <code>string session_key = 3;</code>
     * @return The sessionKey.
     */
    public java.lang.String getSessionKey() {
      java.lang.Object ref = sessionKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * the hex-encoded string of the binary session key
     * </pre>
     *
     * <code>string session_key = 3;</code>
     * @return The bytes for sessionKey.
     */
    public com.google.protobuf.ByteString
        getSessionKeyBytes() {
      java.lang.Object ref = sessionKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * the hex-encoded string of the binary session key
     * </pre>
     *
     * <code>string session_key = 3;</code>
     * @param value The sessionKey to set.
     * @return This builder for chaining.
     */
    public Builder setSessionKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionKey_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the hex-encoded string of the binary session key
     * </pre>
     *
     * <code>string session_key = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionKey() {
      sessionKey_ = getDefaultInstance().getSessionKey();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the hex-encoded string of the binary session key
     * </pre>
     *
     * <code>string session_key = 3;</code>
     * @param value The bytes for sessionKey to set.
     * @return This builder for chaining.
     */
    public Builder setSessionKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionKey_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:helium.iot_config.skf_v1)
  }

  // @@protoc_insertion_point(class_scope:helium.iot_config.skf_v1)
  private static final com.helium.grpc.skf_v1 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.helium.grpc.skf_v1();
  }

  public static com.helium.grpc.skf_v1 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<skf_v1>
      PARSER = new com.google.protobuf.AbstractParser<skf_v1>() {
    @java.lang.Override
    public skf_v1 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<skf_v1> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<skf_v1> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.helium.grpc.skf_v1 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

